#ifndef HTML_CLEANER_CLEANEROPTION_H
#define HTML_CLEANER_CLEANEROPTION_H


enum CleanerOption {
    ATTRIBUTES_OPTION,
    STYLES_OPTION,
    SCRIPTS_OPTION,
    DOCTYPE_OPTION,
    COMMENTS_OPTION
};


#endif //HTML_CLEANER_CLEANEROPTION_H
