(function (lib, img, cjs) {

var p; // shortcut to reference prototypes

// stage content:
(lib._950x200 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Warstwa 1
	this.legal_mc = new lib.legal_bt();
	this.legal_mc.setTransform(810.3,168.6,1.124,1,0,0,0,38.9,10.8);
	new cjs.ButtonHelper(this.legal_mc, 0, 1, 2, false, new lib.legal_bt(), 3);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.legal_mc}]}).wait(270));

	// MASK
	this.display_mc = new lib.display_mc();
	this.display_mc.setTransform(375.1,100.1,1,1,0,0,0,374.9,100);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.display_mc}]}).wait(270));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-14.7,-248.8,1003.5,486.3);


// symbols:
(lib.img00 = function() {
	this.initialize(img.img00);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,950,300);


(lib.img11 = function() {
	this.initialize(img.img11);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,281,360);


(lib.img12 = function() {
	this.initialize(img.img12);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,146,120);


(lib.TXTASDCV = function() {
	this.initialize();

	// Warstwa 3
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AmVCKIAAjOIArAAIAAAMQARgOAWAAQAcAAASAUQATAUAAAeQAAAfgTAUQgSAUgfAAQgUAAgQgJIAABMgAlqgcIAAA9QAMAJANAAQAQAAAJgLQAKgLAAgUQAAgSgJgLQgIgLgQAAQgNAAgOAMgAEoAzQgSgVAAgeQAAgeATgUQATgUAdAAQATAAARAIIAAhIIArAAIAADLIgrAAIAAgLQgRANgVAAQgcAAgTgUgAFMgeQgKAMAAASQAAATAJAMQAJALAQAAQANAAAMgLIAAhAQgMgIgMAAQgQAAgJALgAC6BHIgjhJIgjBJIgUAAIg/iLIAtAAIAdBLIAehLIAbAAIAfBLIAdhLIAtAAIg/CLgAgTA4QgWAPgXAAQgRAAgLgKQgLgKAAgNQAAgTAMgLQAMgJA6gRQABgXgZAAQgcAAgXAXIAAgkQAcgQAgAAQA5AAgBAqIAAA9QAAAJAIAAQAFAAALgHIAAAYQgVAMgUAAQgSAAgEgPgAgzAPQgIAGAAAKQAAAGAEAEQAFAFAFAAQAMAAAMgLIAAghQgWAHgIAGgApJA0IAAgsQAVANAQAHQAQAGARAAQAeAAAAgTQAAgGgGgGQgGgEgXgIQgXgIgOgHQgNgHgKgNQgJgNAAgVQAAgaAVgQQAWgRAjAAQAhAAAkAQIAAAoQgpgSgXAAQgOAAgJAFQgHAEgBAIQABAGAFAFQAGAFAWAJQAYAIANAHQAOAHAKANQAJANABASQgBAdgVARQgWAQgjAAQgmAAgkgTgAHABFIBIhrIhBAAIAAgeICHAAIhGBrIBGAAIAAAegAjlBFIAAiJIAsAAIAAAoIABAAQASgqAaAAQAMAAAQAMIgMAnQgQgLgJAAQgPAAgLATQgKARAAADIAAA8gAHvhYIAXgsIAxAAIgxAsg");
	this.shape.setTransform(62.1,24.3);

	this.addChild(this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(3.1,10.5,118.1,27.7);


(lib.separacja = function() {
	this.initialize();

	// Warstwa 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#505153").s().p("Al+AEIAAgHIL9AAIAAAHg");
	this.shape.setTransform(38.4,0.5);

	this.addChild(this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(0,0,76.7,0.9);


(lib.ludziki = function() {
	this.initialize();

	// mask (mask)
	var mask = new cjs.Shape();
	mask._off = true;
	mask.graphics.p("AANc9QqsgSqzgnQAEgdAMgtIADgJQAghmA+hgQA+hgB+iXIBxiEQgPgYgEgIQgCgFADgjIAEgpIAAgaIADgXQACgQAIgfQAJghAHgKQADgWARgqQARgpATgdQABgMAOgnIAOgjQAJgRADgJIAHgUQAGgZAIgUQgEgkAPhHQAQhJAXgtIBGh+QAwhaAMgkQANgpAphlQAlhdANgdQAMgZAOg2QAQg5AJg4QAJgxBBh9QAjhDAphHQA+hoBDgzQAygmAtgEQAzgEAsAdQAXARAfAkQAgAKAJgSQAEgJgCgLQgUgDgSgJQgNgGgUgNQgRgNgIgHIgCgCIgOg+QhChdgphuIhvhAIASAAIgVgSIAPgMIgYgiQAHgGAHgDQAFgDAZgEIAeAZIAEgOIAQAaQAKg1ArgpQAAhJgbAEIAAgTQANgfASABQAJhKAjhBIANAiIAKg5IA8giIgMAAIAOgCQBLhHAhg3QAgg4AJgYIAFAAIBNBPQBwANBrAfQA8ARA3AkQAXgeADgtQgMgyghggIABAAQAhASASAXQAPATAKAfQAAAigCARQgDAVgHAMQAaASAuAvQAtAvAuAtQAYAXAXAUIgPgLQgYgPgbgKQBBA7gNBWQgHASgGARQgKADgBACQgCACAIADIACACQgIAagEAaIA8BLIgCABIg6gvIgGAzQgFgBgEAFQARAUgSAwQgIAXgMAUIgFAcQgHAggLAVQgMAWgQAJQgNAHgJgDQgLAzg7BIIg5A+IgZBIQgcBQgKAnQgVBLAbBGQBBgLA3ADQAkACAxAKQCVAgBCAJQAXAFANAYQAHAMAGATIApBAQAFAGAKAWQAKAXAFAGIAKANQAFAFADAGQAFAMAABlQAEALgCANIgFAbQAFATgIAJIgJAFIgMAVIAAABQgHAsg0AIIABABIgBAAQAVAlAEArQACAagCAuQAAAWgCAnQgBAbACAGQABAEAOAVIAEAGQAIAjgWAfQgXAegCAGIABAAIgDACQAaAmgFAYQgCAJgSAbQADAMgBAnIgBAfIgEAJQgEALAAAIQAAAGgHANQgIANAAAGQgCANgcArIADAHQACAIgHAJQgGAIgCgBQAAgBAAAAQgBAAAAAAQAAAAAAAAQAAAAAAABIgEAPQAAADgGAGQgGAGAAAEIgCAdIgCALIAAAJQgBADgDAEQgDAEgBADIgCAKIgCAJIgBAJIAAASQAAAKgCAKIABAOQABAFgCAHIgCAMIgDAJQgDALABAIQAAAEgEADQgFACgBAGIgJASIgEAEQgFAGgCAFIgDAKQgCAEgDABQgDAAgEAEQgEAEgGADQgKAFgLADQgdAGgzABQAnA6ARAnQAJATABAIIAlAfIA9A1IBzBsQBlBaAyAcQBwA/A5BTIAJAOQAUAhAGAYQARBSsJAAQj9AAlRgIg");
	mask.setTransform(179.3,122);

	// Warstwa 2
	this.instance = new lib.img11();
	this.instance.setTransform(36.2,-66.2,1.001,1.001);

	this.instance.mask = mask;

	this.addChild(this.instance);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(36.2,-66.2,281.3,360.3);


(lib.logo100 = function() {
	this.initialize();

	// mask (mask)
	var mask = new cjs.Shape();
	mask._off = true;
	mask.graphics.p("An1GQQjQimAAjqQAAjpDQimQDQimElAAQEmAADQCmQDQCmAADpQAADqjQCmQjQCmkmAAQklAAjQimg");
	mask.setTransform(73.4,60.9);

	// Warstwa 1
	this.instance = new lib.img12();
	this.instance.setTransform(0,0,0.999,0.999);

	this.instance.mask = mask;

	this.addChild(this.instance);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(0,0,145.9,119.9);


(lib.legal_bt = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Warstwa 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#C82059").s().p("AmDBsIAAjXIMHAAIAADXg");
	this.shape.setTransform(38.9,10.8);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[]}).to({state:[{t:this.shape}]},3).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,0,0);


(lib.gvc = function() {
	this.initialize();

	// Warstwa 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#C82059").s().p("AtIELQhugBhOhOQhOhOAAhuIAAAAQAAhtBOhPQBOhOBuABIaQAAQBugBBPBOQBOBPAABtIAAAAQAABuhOBOQhPBOhuABg");
	this.shape.setTransform(-130.8,18.2);

	this.addChild(this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-241.6,-8.4,221.5,53.4);


(lib.gradrad = function() {
	this.initialize();

	// Warstwa 1
	this.shape = new cjs.Shape();
	this.shape.graphics.rf(["#FFFFFF","rgba(255,255,255,0.435)","rgba(255,255,255,0)"],[0.2,0.694,0.945],0,0,0,0,0,86.9).s().p("ApgJhQj9j8AAllQAAlkD9j8QD8j9FkAAQFlAAD8D9QD9D8AAFkQAAFlj9D8Qj8D9llAAQlkAAj8j9g");
	this.shape.setTransform(86.2,86.2);

	this.addChild(this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(0,0,172.5,172.5);


(lib.circ1 = function() {
	this.initialize();

	// Warstwa 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AltFtQiXiXAAjWQAAjVCXiYQCYiXDVAAQDWAACXCXQCYCYAADVQAADWiYCXQiXCYjWAAQjVAAiYiYg");
	this.shape.setTransform(51.8,51.8);

	this.addChild(this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(0,0,103.6,103.6);


(lib.c1 = function() {
	this.initialize();

	// Warstwa 1
	this.instance = new lib.img00();

	this.addChild(this.instance);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(0,0,950,300);


(lib.txt298 = function() {
	this.initialize();

	// txt
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#424345").s().p("ApNBuIAAikIAjAAIAAAKQANgMASAAQAVAAAPARQAPAPABAYQgBAZgPAQQgOAQgZAAQgPAAgNgHIAAA8gAoqgWIAAAwQAJAIALAAQANAAAHgJQAHgKAAgPQAAgOgHgIQgGgJgNAAQgLAAgKAJgAtlBPQASgDAAgaIAAhoIAiAAIAABwQAAAXgLAOQgLANgTACgAEYBsIAghHIgrhbIAlAAIAYA3IAZg3IAkAAIhKCigAYkAzQgGgGAAgJQAAgIAGgGQAHgHAIAAQAJAAAGAHQAGAGAAAIQAAAJgGAGQgGAGgJAAQgIAAgHgGgAWoAqQgRgQAAgaQAAgXAQgQQAQgRAaAAQAaAAAQASQAQAQgBAbIhPAAQABAPAKAIQAJAIAQAAQAUAAAVgPIAAAVQgTAPgeAAQgdAAgSgPgAW7gLIAxAAQgDgYgWAAQgVAAgDAYgAVRA5Igbg6IgdA6IgPAAIgzhvIAkAAIAXA8IAZg8IAVAAIAYA8IAYg8IAkAAIgzBvgARsApQgSgQAAgZQABgZARgPQASgQAbAAQAaAAASAQQASAPAAAZQAAAbgSAPQgTAPgZAAQgbAAgSgQgASGgaQgGAKgBAQQAAAkAaAAQAZAAAAgkQAAgjgZAAQgMAAgHAJgAP2AxIAAgZQAVAKAPAAQARAAAAgJQAAgCgDgEQgEgCgRgHQgSgHgGgGQgHgJAAgKQAAgPAMgJQANgKAVAAQATAAARAIIAAAZQgVgMgQAAQgNAAAAAIQAAABAAAAQAAABABAAQAAABAAAAQABABABABQACACASAHQASAHAHAHQAHAJAAALQAAARgMAKQgLAJgWAAQgXAAgRgIgAMrAsQgSANgTAAQgMAAgKgIQgJgIAAgLQABgOAJgJQAJgHAvgOQABgSgUgBQgWABgTASIAAgdQAWgNAaAAQAvAAAAAiIAAAwQAAAIAGAAQAEAAAJgHIAAAUQgSAKgOAAQgRAAgDgNgAMSANQgIAEABAIQAAAEADAEQADAEAFgBQAKABAJgJIAAgbQgRAGgGAGgAC4AuIAAAJIgjAAIAAiiIAjAAIAAA8QANgJAPAAQAYAAAPAQQAPAQABAYQgBAZgOAQQgOAQgYAAQgQAAgOgLgAC4gZIAAAxQAKAKAKAAQANAAAHgKQAHgJAAgPQAAgPgIgJQgHgJgMAAQgKAAgKAIgAAdAqQgRgQAAgaQAAgXAQgQQAQgRAZAAQAaAAARASQAQAQgBAbIhPAAQABAPAJAIQAKAIAQAAQAUAAAVgPIAAAVQgUAPgdAAQgeAAgRgPgAAwgLIAwAAQgDgYgVAAQgWAAgCAYgAkiAuQgLgKAAgVIAAgtIgQAAIAAgGIAug1IAEAAIAAAjIApAAIAAAYIgpAAIAAAsQAAAIAEAFQAFAEAIABQALgBANgGIAAAZQgRAHgQAAQgUAAgLgLgAm0ApQgSgQAAgZQAAgZASgPQASgQAbAAQAZAAATAQQASAPAAAZQAAAbgSAPQgTAPgZAAQgcAAgRgQgAmagaQgHAKAAAQQAAAkAaAAQAZAAgBgkQABgjgZAAQgMAAgHAJgAsIAqQgRgQAAgaQAAgXARgQQAPgRAaAAQAZAAARASQAQAQAAAbIhQAAQABAPAJAIQAKAIAQAAQAUAAAWgPIAAAVQgVAPgdAAQgdAAgSgPgAr1gLIAwAAQgCgYgVAAQgWAAgDAYgAvXApQgRgQgBgZQABgZASgPQARgQAbAAQAaAAASAQQASAPAAAZQAAAbgSAPQgTAPgZAAQgbAAgSgQgAu8gaQgIAKAAAQQABAkAZAAQAZAAAAgkQAAgjgZAAQgMAAgGAJgAwvA5Igbg6IgcA6IgQAAIgyhvIAkAAIAWA8IAZg8IAVAAIAZA8IAXg8IAkAAIgyBvgA1+AsQgTANgRAAQgNAAgKgIQgIgIgBgLQAAgOAKgJQAJgHAvgOQACgSgVgBQgWABgTASIAAgdQAWgNAaAAQAvAAAAAiIAAAwQAAAIAGAAQAEAAAJgHIAAAUQgSAKgPAAQgQAAgDgNgA2YANQgGAEgBAIQAAAEAEAEQADAEAFgBQAKABAJgJIAAgbQgRAGgHAGgAO5A3IAAhBQABgXgSAAQgMAAgMASIAABGIgiAAIAAhtIAiAAIAAAQQAQgSAUAAQASAAALALQALALAAAVIAABEgAKuA3IAAhBQAAgXgRAAQgNAAgLASIAABGIgjAAIAAhtIAjAAIAAAQQAPgSAUAAQASAAALALQAMALAAAVIAABEgAIhA3IAAhtIAkAAIAABtgAHdA3IAAhVIgPAAIAAgYIAPAAIAAgFQAAgYAOgNQANgNAWAAIAVACIAAAHIACgDQAGgGAIAAQAIAAAFAGQAGAGAAAHQAAAJgGAFQgFAGgIgBQgIABgGgGIgCgDIgQgBQgTAAAAATIAAAHIAQAAIAAAYIgQAAIAABVgAhvA3IA5hVIg0AAIAAgYIBqAAIg2BVIA2AAIAAAYgAjQA3IAAhtIAjAAIAAAgIAAAAQAQgiAUAAQAJAAAOAKIgKAfQgNgJgHAAQgNAAgHAPQgJANAAADIAAAwgAzqA3IAAiDIg7AAIAAgfICgAAIAAAfIg7AAIAACDgA37A3IAAhBQAAgXgRAAQgNAAgMASIAABGIgiAAIAAhtIAiAAIAAAQQAQgSAUAAQASAAAMALQALALAAAVIAABEgAYsABIgHggQgGgeAAgWQAAgaAUAAQAUAAAAAaQAAARgGAfQgFAhgCACQgCAGgFAAQgEAAgDgFgAtPhMQgGgFAAgJQAAgHAGgGQAFgGAIAAQAIAAAFAGQAGAGABAHQgBAJgGAFQgFAGgIgBQgIABgFgGg");
	this.shape.setTransform(162.3,23.2);

	this.addChild(this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(1.5,12.1,321.7,22.1);


(lib.txt297 = function() {
	this.initialize();

	// txt
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#424345").s().p("AIsBuIAAikIAjAAIAAAKQAOgMARAAQAWAAAPARQAPAPAAAYQAAAZgPAQQgPAQgZAAQgPAAgNgHIAAA8gAJPgWIAAAwQAKAIAKAAQANAAAHgJQAIgJgBgQQAAgOgGgIQgHgJgNAAQgKAAgLAJgATJApQgPgQAAgZQAAgYAPgQQAPgQAYAAQAPAAAOAHIAAg6IAiAAIAACiIgiAAIAAgJQgOALgSAAQgVAAgPgQgATkgYQgHAKAAAOQAAAPAHAJQAIAKAMAAQAKAAALgKIAAgyQgKgHgKAAQgNABgIAIgARIAqQgSgQAAgaQAAgXARgQQAPgRAaAAQAZAAARASQARAQgBAbIhQAAQABAPAJAIQAKAIAQAAQAUAAAWgPIAAAVQgVAPgdAAQgdAAgRgPgARagLIAwAAQgCgYgVAAQgWAAgDAYgAOqA5Igcg6IgcA6IgPAAIgzhvIAkAAIAXA8IAZg8IAVAAIAYA8IAYg8IAkAAIgzBvgALFApQgSgQAAgZQABgZARgPQASgQAbAAQAaAAASAQQASAPAAAZQAAAbgSAPQgTAPgZAAQgbAAgSgQgALfgaQgHAKAAAQQABAkAZAAQAZAAAAgkQAAgjgZAAQgMAAgHAJgAGqApQgPgQAAgZQAAgYAPgQQAPgQAYAAQAOAAAOAHIAAg6IAjAAIAACiIgjAAIAAgJQgNALgRAAQgXAAgOgQgAHGgYQgIAKAAAOQAAAPAIAJQAGAKANAAQAKAAAKgKIAAgyQgJgHgKAAQgNABgHAIgAEeApQgRgQAAgZQAAgZASgPQARgQAbAAQAbAAARAQQASAPAAAZQAAAbgSAPQgSAPgaAAQgbAAgSgQgAE5gaQgHAKAAAQQAAAkAZAAQAaAAAAgkQAAgjgaAAQgMAAgGAJgACNAsQgSANgSAAQgNAAgJgIQgJgIAAgLQAAgOAKgJQAIgHAwgOQABgSgUgBQgWABgUASIAAgdQAXgNAZAAQAwAAAAAiIAAAwQAAAIAFAAQAFAAAJgHIAAAUQgSAKgPAAQgRAAgDgNgAB0ANQgHAEAAAIQAAAEAEAEQADAEAFgBQAJABAKgJIAAgbQgRAGgHAGgAlIApQgRgQAAgZQgBgZATgPQARgQAbAAQAaAAASAQQASAPAAAZQAAAbgSAPQgSAPgaAAQgcAAgRgQgAktgaQgIAKABAQQgBAkAaAAQAZAAAAgkQAAgjgZAAQgMAAgGAJgAoLAuQgLgKAAgUIAAguIgQAAIAAgHIAug0IAEAAIAAAjIApAAIAAAYIgpAAIAAAsQAAAIAEAFQAFAEAIABQALgBANgGIAAAZQgRAHgQAAQgUAAgLgLgAqFAxIAAgZQAWAKAOAAQARAAAAgJQAAgCgDgEQgEgCgRgHQgSgHgGgGQgHgJAAgKQAAgPANgJQAMgKAUAAQAVAAAPAIIAAAZQgUgMgRAAQgMAAAAAIQAAABAAAAQAAABABAAQAAABAAAAQABABAAABQADACASAHQARAHAHAHQAIAJAAALQAAARgLAKQgMAJgWAAQgWAAgSgIgAt5AqQgSgQAAgaQAAgXASgQQASgRAbAAQASAAATAIIAAAZQgOgHgOAAQgPAAgKAJQgJAIAAANQAAAOAJAKQAJAJAPAAQALgBAUgHIAAAZQgUAHgSAAQgdAAgRgPgAv+AqQgRgQAAgaQAAgXAQgQQAQgRAaAAQAZAAARASQAQAQgBAbIhPAAQABAPAJAIQAKAIAQAAQAUAAAVgPIAAAVQgUAPgdAAQgdAAgSgPgAvrgLIAwAAQgDgYgVAAQgWAAgCAYgAzsAxIAAgZQAVAKAPAAQARAAAAgJQAAgCgDgEQgEgCgRgHQgSgHgGgGQgHgJAAgKQAAgPAMgJQANgKAVAAQATAAARAIIAAAZQgVgMgQAAQgNAAAAAIQAAABAAAAQAAABABAAQAAABAAAAQABABABABQADACARAHQASAHAHAHQAHAJAAALQAAARgMAKQgLAJgWAAQgXAAgRgIgA05A5Igcg6IgcA6IgPAAIgzhvIAkAAIAXA8IAZg8IAVAAIAYA8IAYg8IAkAAIgzBvgAVCA3IA5hVIg0AAIAAgYIBsAAIg4BVIA4AAIAAAYgAP7A3IAAhtIAjAAIAABtgAAQA3IAAhBQAAgXgQAAQgLAAgMASIAABGIgiAAIAAhtIAiAAIAAAQQAPgSATAAQARAAAMALQALALAAAVIAABEgAh5A3IAAhBQAAgXgRAAQgNAAgMASIAABGIgjAAIAAhtIAjAAIAAAQQAQgSAUAAQASAAALALQAMALgBAVIAABEgAm5A3IAAhtIAjAAIAAAgIAAAAQAQgiAUAAQAJAAAOAKIgKAfQgNgJgHAAQgNAAgHAPQgJANAAADIAAAwgArBA3IAAg+QAAgXgSAAQgMgBgMASIAABEIgiAAIAAiiIAiAAIAABGIABAAQAOgTAVAAQASAAALALQAMALAAAVIAABEgAyMA3IA5hVIg0AAIAAgYIBsAAIg4BVIA4AAIAAAYgAVnhGIASgjIAoAAIgoAjgAP/hMQgGgFAAgJQAAgHAGgGQAGgGAHAAQAJAAAFAGQAGAGAAAHQAAAJgGAFQgFAGgJgBQgHABgGgGg");
	this.shape.setTransform(146,18.7);

	this.addChild(this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(0,7.6,292,22.1);


(lib.txt296 = function() {
	this.initialize();

	// txt
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#C82059").s().p("AGdBCQgPgXAAgnQAAgmAPgWQAPgWAaAAQAaAAAPAWQAOAXAAAkQAAAogOAWQgOAXgaAAQgbAAgPgWgAG3gkQgEALAAAfQAAAbAEAMQAFAMAKAAQAKAAAEgMQAFgMAAggQAAgagEgLQgFgLgKAAQgKAAgFALgAEZBIQgPgQAAgaQAAgcAWgiIAcguIApAAIgmA+IALgCQASAAANAPQANAMAAAXQAAAYgPAQQgQAQgXAAQgYAAgPgQgAEzAPQgFAHAAALQAAAMAFAGQAFAGAJAAQAIAAAFgGQAFgHAAgLQAAgLgFgHQgFgGgIAAQgJAAgFAGgACJBPIAAggQASANAQAAQAMAAAHgGQAHgGAAgKQAAgJgHgHQgHgGgLgBIAAgbQAKAAAGgFQAGgGAAgIQAAgIgHgGQgGgFgKAAQgOAAgQAIIAAgdQAQgHAVAAQAYAAAOALQAPALAAASQAAAZgZANQAdAJAAAfQAAAWgQANQgQANgaAAQgWAAgSgJgAg6BIQgRgQAAgaQAAgaASgOQARgPAbAAQAYAAASAPQASANAAAcQAAAbgSAPQgSAPgYAAQgbAAgSgQgAgfADQgHAKAAARQAAAlAZAAQAXAAAAglQAAgigXAAQgMAAgGAHgAiYBNQgLgKAAgVIAAguIgQAAIAAgGIAug0IAFAAIAAAjIAoAAIAAAXIgoAAIAAAtQAAAIAEAFQAFAEAIAAQALAAAMgGIAAAZQgRAHgPAAQgUAAgMgLgAm2BIQgRgQAAgaQAAgaASgOQARgPAbAAQAaAAASAPQASANAAAcQAAAbgSAPQgSAPgaAAQgbAAgSgQgAmbADQgHAKAAARQAAAlAZAAQAZAAAAglQAAgigZAAQgMAAgGAHgAjnBWIAAhEQAAgUgRAAQgNAAgMAQIAABIIgiAAIAAhtIAiAAIAAAQQAQgSAUAAQASAAALALQAMALAAASIAABHgAnyBWIhBhNIAABNIgpAAIAAiiIApAAIAABKIA0hKIAsAAIg1BMIBIBWgAIdgXQgLgLAAgPQAAgQALgLQALgLAQAAQAPAAALALQALALAAAQQAAAPgLALQgLALgPAAQgQAAgLgLgAIsg9QgFAEAAAIQAAAGAFAFQAFAFAHAAQAHAAAFgFQAFgFAAgGQAAgIgFgEQgFgFgHAAQgHAAgFAFg");
	this.shape.setTransform(62.4,16.5);

	this.addChild(this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(1.8,7.7,121.2,17.7);


(lib.txt33 = function() {
	this.initialize();

	// txt
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#505153").s().p("ARYBjQALgLAAgRIAAgEQgNgFAAgNQAAgJAGgFQAGgGAJAAQALAAAHAIQAHAIAAANQAAASgNAOQgMAPgTACgAN5AsQgQgXAAgnQAAgqAQgXQAQgXAaAAQAcAAAPAXQAPAYAAAoQAAAngPAYQgPAXgbAAQgcAAgPgXgAOUg+QgFALAAAiQAAAbAFANQAFAMAKAAQALAAAEgMQAFgNAAggQAAgcgFgMQgEgMgLAAQgKAAgFAMgALvAyQgQgRAAgaQAAgcAYglIAdgwIAqAAIgnBAIALgBQATAAAOAPQANAPAAAWQAAAZgQAQQgQARgYAAQgZAAgQgRgAMKgHQgFAHAAAKQAAAMAFAGQAFAHAJAAQAJAAAGgHQAFgHAAgLQAAgKgGgHQgFgHgJAAQgJAAgFAHgAJZA5IAAghQATAOARAAQAMAAAHgGQAIgHAAgKQAAgKgIgFQgHgGgMgBIAAgeQALAAAGgGQAGgGAAgIQAAgJgGgFQgHgGgLAAQgOAAgRAIIAAgeQARgHAWAAQAYAAAPAMQAQALAAATQAAAZgaAOQAeAMAAAeQAAAXgQANQgRAOgbAAQgXAAgTgKgAGMAyQgSgQAAgbQAAgZASgRQATgQAcAAQAbAAATAQQATAQAAAaQAAAdgUAPQgTAQgaAAQgdAAgSgRgAGngTQgHAJAAARQAAAmAbAAQAaAAAAgnQAAgjgaAAQgNAAgHAKgAEqA4QgMgLAAgVIAAgwIgQAAIAAgHIAwg2IAFAAIAAAlIAqAAIAAAYIgqAAIAAAuQAAAIAEAFQAFAFAIAAQALAAAOgGIAAAaQgSAHgQAAQgVAAgMgLgAAAAyQgQgQAAgbQAAgZAQgRQATgQAcAAQAbAAATAQQATAQAAAaQAAAdgUAPQgTAQgaAAQgdAAgSgRgAAbgTQgHAJAAARQAAAmAbAAQAaAAAAgnQAAgjgaAAQgNAAgHAKgApvAyQgSgQAAgbQAAgZASgRQATgQAcAAQAbAAATAQQATAQAAAaQAAAdgUAPQgTAQgaAAQgdAAgSgRgApUgTQgHAJAAARQAAAmAbAAQAaAAAAgnQAAgjgaAAQgNAAgHAKgArPBDIgdg/IgdA/IgRAAIg0hzIAlAAIAYA9IAag9IAWAAIAaA9IAYg9IAlAAIg0BzgAuUA4QgMgLAAgVIAAgwIgQAAIAAgHIAwg2IAFAAIAAAlIAqAAIAAAYIgqAAIAAAuQAAAIAEAFQAFAFAIAAQALAAAOgGIAAAaQgSAHgQAAQgVAAgMgLgAxnApQgcgaAAghQAAgjAcgbQAbgaArAAQAsAAAbAaQAbAbAAAjQAAAhgcAaQgbAagrAAQgrAAgbgagAxIg4QgPAOAAAYQAAAVAPAOQAPAPAYAAQAYAAAPgPQAPgOAAgVQAAgYgPgOQgPgOgYAAQgYAAgPAOgADXBBIAAhFQAAgXgSAAQgNAAgMATIAABJIgkAAIAAhxIAkAAIAAAQQAQgTAVAAQASAAANAMQALALAAAVIAABIgAg+BBIhDhOIAABOIgrAAIAAipIArAAIAABNIA2hNIAuAAIg3BQIBLBZgAmBBBIA7hZIg2AAIAAgYIBxAAIg7BYIA7AAIAAAZgAnmBBIAAhxIAkAAIAAAgIAAAAQAQgjAVAAQAKAAAOALIgKAgQgNgJgIAAQgNAAgIAQQgJANAAADIAAAygAP7gsQgMgKAAgPQAAgQAMgKQAMgLATAAQATAAAMAKQAMALAAAPQAAAQgMAKQgMAKgTAAQgTAAgMgKgAQLhFQAAAVAPAAQAPAAAAgXQAAgUgQAAQgOAAAAAWgApUhCIASgkIAqAAIgqAkg");
	this.shape.setTransform(116.8,14.5);

	this.addChild(this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(1.2,3.8,231.3,21.5);


(lib.txt32 = function() {
	this.initialize();

	// txt
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#505153").s().p("AyqBzIAAirIAkAAIAAAKQAOgNATAAQAWABAQARQAPAQAAAZQAAAagPARQgPAQgaAAQgQAAgOgHIAAA/gAyGgYIAAA0QALAHAKAAQANAAAIgJQAHgKAAgQQABgPgIgJQgGgJgOAAQgLAAgLAJgAhWBhQgHgIAAgNQAAgJAEgJQgJgCgDgKQgTANgSAAQgOAAgKgIQgJgJAAgNQAAgIAEgHQAEgGAHgFQAHgDAPgFIAggKQAAgJgFgGQgEgEgLAAQgYAAgTATIAAgdQAXgOAcgBQARAAAMAGQALAFAEAHQAEAIAAAOIAAAsQAAAFABACQABABAAAAQABAAAAAAQABABABAAQAAAAABAAQAEAAAKgGIAAAVQgKAFgMADQgDAIAAADQABAHAEADQAEADAFABIAJgBIAAATQgJAEgKAAQgMAAgHgHgAhvAEQgNAGgFAEQgFAEAAAIQAAAFAEAEQADADAFgBQAKAAAKgIIAAgcgAj5AwQgMgLAAgVIAAgwIgRAAIAAgHIAxg2IAEAAIAAAlIArAAIAAAYIgrAAIAAAuQAAAJAFAFQAFAEAIAAQALABAOgHIAAAaQgSAHgRAAQgUAAgMgLgAnEAuQgTANgSAAQgOAAgKgJQgIgIgBgLQAAgPAKgJQAKgHAxgPQABgTgVAAQgYAAgTATIAAgdQAXgOAbgBQAxAAAAAjIAAAzQAAAIAGAAQAEAAAJgHIAAAUQgRALgQAAQgRAAgEgNgAneAMQgHAGAAAIQAAAFAEADQADADAFAAQAKAAAKgIIAAgcQgTAHgGAEgAtCArQgTgQABgbQAAgZASgQQASgRAdgBQASABAUAHIAAAbQgPgIgOAAQgQAAgKAJQgKAJAAAOQAAAPAKAJQAJAKAQAAQALgBAVgHIAAAaQgVAHgRAAQgfAAgSgQgAuVAuQgSANgUAAQgNAAgJgJQgJgIAAgLQAAgPAJgJQAJgHAygPQABgTgVAAQgXAAgUATIAAgdQAXgOAbgBQAxAAAAAjIAAAzQAAAIAGAAQAFAAAIgHIAAAUQgSALgPAAQgRAAgEgNgAuvAMQgHAGAAAIQAAAFADADQAEADAFAAQAKAAAKgIIAAgcQgTAHgGAEgASBA5IAAhpIgvA0IgGAAIgug0IAABpIgqAAIAAipIAlAAIA2A/IA3g/IAlAAIAACpgANVA5IAAipIB8AAIAAAgIhRAAIAAAkIBOAAIAAAeIhOAAIAAAoIBTAAIAAAfgAMDA5IAAipIArAAIAACpgAK7A5IhDhOIAABOIgrAAIAAipIArAAIAABOIA2hOIAvAAIg4BQIBLBZgAH8A5IAAipIAqAAIAACpgAFgA5IAAipIAqAAIAACKIBYAAIAAAfgACxA5IAAipIBKAAQAaAAAQANQAPANAAARQAAAXgYAMQASAEAJAMQAKALgBAOQABAWgQAOQgPAOgeAAgADcAaIAYAAQARAAAHgFQAIgFAAgLQAAgHgIgFQgGgGgMAAIgeAAgADcgsIAWAAQAKAAAGgFQAGgGAAgHQAAgIgGgFQgGgGgKABIgWAAgAAlA5IAAhxIAlAAIAABxgAl9A5IAAhxIAkAAIAAAgIAAAAQAQgjAVAAQAKAAAOALIgKAgQgNgIgJAAQgMAAgIAPQgKANABADIAAAygAo6A5Igtg5IgBAAIAAA5IgkAAIAAipIAkAAIAABwIABAAIAtg4IAqAAIgtA4IAvA5gAwXA5IAAg5IgTANIAAgbIATgQIAAhSIAkAAIAAA4IAUgPIAAAdIgUAQIAABTgAAphPQgGgHAAgIQAAgIAGgGQAGgFAIgBQAJABAFAFQAGAGAAAIQAAAIgGAHQgFAFgJAAQgIAAgGgFgAsshKIASgkIAqAAIgqAkg");
	this.shape.setTransform(119.7,17.4);

	this.addChild(this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(0.1,5.9,239.1,23);


(lib.txt31 = function() {
	this.initialize();

	// txt
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#C82059").s().p("An0BiQAWgDAAghIAAiCIAsAAIAACNQAAAcgPARQgOARgYADgAxBCHIAohZIg2hyIAuAAIAeBGIAfhGIAuAAIhdDLgAO2AsQgTgcAAgvQAAgyATgcQATgcAgAAQAhAAASAcQASAcAAAwQAAAwgRAcQgSAcghAAQgiAAgSgbgAPXhUQgGAOAAApQAAAgAGAPQAGAPAMAAQANAAAFgPQAGgPAAgnQAAgigGgOQgFgOgNAAQgMAAgGAOgAMRAzQgTgUAAgfQAAgiAcgtIAjg6IAzAAIgwBOIAOgCQAXAAAQASQARASAAAbQAAAegUATQgTAUgdAAQgeAAgTgUgAMygRQgHAIAAAMQAAAOAHAIQAGAIALAAQAKAAAGgIQAHgIAAgOQAAgMgHgIQgGgJgLAAQgKAAgGAJgAJdA8IAAgoQAXAQAUAAQAOAAAJgHQAJgIAAgMQAAgKgJgIQgIgIgPAAIAAgkQANAAAIgIQAHgHAAgKQAAgKgIgHQgIgHgNAAQgRAAgUAKIAAgkQAUgJAbAAQAdAAASAPQASANAAAXQAAAegeARQAkAOAAAkQAAAcgUAQQgUAQghAAQgbAAgXgLgAGkA6QgOgNAAgZIAAg6IgUAAIAAgIIA6hBIAFAAIAAArIAzAAIAAAeIgzAAIAAA3QAAAKAGAGQAFAGAKAAQAOAAAQgIIAAAgQgVAIgUAAQgZAAgOgNgAD6A0QgWgUAAggQAAgeAUgUQAVgUAgAAQAgAAAUAVQAUAVgBAiIhjAAQABATAMAKQAMALAUAAQAZAAAbgUIAAAbQgZASglAAQgkAAgWgTgAESgOIA8AAQgEgfgaAAQgbAAgDAfgACNBHIgjhJIgjBJIgUAAIg9iLIArAAIAdBLIAfhLIAaAAIAfBLIAdhLIAtAAIg/CLgAhAA4QgWAPgXAAQgQAAgMgKQgLgKAAgNQAAgTAMgLQAMgJA6gRQACgXgaAAQgbAAgYAXIAAgkQAcgQAgAAQA7AAAAAqIAAA9QAAAJAHAAQAFAAAKgHIAAAYQgUAMgTAAQgVAAgEgPgAhfAPQgJAGAAAKQAAAGAEAEQAFAFAFAAQANAAALgLIAAghQgVAHgIAGgAozA4QgWAPgXAAQgQAAgMgKQgLgKAAgNQAAgTAMgLQAMgJA6gRQACgXgaAAQgbAAgYAXIAAgkQAcgQAgAAQA7AAAAAqIAAA9QAAAJAHAAQAFAAALgHIAAAYQgVAMgTAAQgVAAgEgPgApSAPQgJAGAAAKQAAAGAEAEQAFAFAFAAQANAAALgLIAAghQgVAHgIAGgAuoA9IAAgeQAaALASAAQAWAAAAgKQAAgEgEgDQgEgEgWgIQgXgJgIgJQgIgKAAgNQAAgTAQgMQAPgLAaAAQAZAAAUAKIAAAfQgZgQgVAAQgQAAAAALQAAADADADQAEACAWAJQAWAJAJAJQAJAMAAANQAAAWgPAMQgPALgbAAQgcAAgVgKgAU/BFIAAhGIgXARIAAggIAXgTIAAhjIArAAIAABDIAXgTIAAAjIgXATIAABlgASVBFIBHhrIhAAAIAAgeICHAAIhHBrIBHAAIAAAegAjbBFIAAhTQAAgbgWAAQgPAAgPAXIAABXIgsAAIAAiJIAsAAIAAAUQATgWAaAAQAVAAAPANQAOAOAAAaIAABWgArBBFIg2hEIgBAAIAABEIgrAAIAAjLIArAAIAACGIABAAIA1hEIAzAAIg2BEIA5BFgAzmBFIBHhrIhAAAIAAgeICHAAIhHBrIBHAAIAAAegA1+BFIAAiJIAsAAIAACJgAnZhgQgHgHAAgKQAAgJAHgHQAHgIAKAAQAKAAAHAIQAHAHAAAJQAAAKgHAHQgHAIgKAAQgKAAgHgIgA15hgQgHgHAAgKQAAgJAHgHQAHgIAKAAQAKAAAHAIQAHAHAAAJQAAAKgHAHQgHAIgKAAQgKAAgHgIg");
	this.shape.setTransform(151.6,18.3);

	this.addChild(this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(10.7,4.5,282,27.7);


(lib.txt12 = function() {
	this.initialize();

	// txt
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#C82059").s().p("ADQCKIAAjOIArAAIAAAMQASgOAWAAQAbAAATAUQATAUAAAeQAAAfgTAUQgTAUgfAAQgTAAgRgJIAABMgAD7gcIAAA9QANAJANAAQAQAAAJgLQAKgLAAgUQAAgSgJgLQgJgLgQAAQgNAAgOAMgAFxCHIAphZIg2hyIAuAAIAdBGIAghGIAuAAIheDLgAPhBAQgIgIAAgLQAAgKAIgIQAIgIALAAQAKAAAIAIQAIAIAAAKQAAALgIAIQgIAHgKAAQgLAAgIgHgALUA4QgWAPgXAAQgRAAgLgKQgLgKAAgNQAAgTAMgLQAMgJA6gRQABgXgZAAQgcAAgXAXIAAgkQAcgQAgAAQA7AAgBAqIAAA9QAAAJAIAAQAFAAALgHIAAAYQgVAMgUAAQgUAAgEgPgAK0APQgIAGAAAKQAAAGAEAEQAFAFAFAAQAMAAAMgLIAAghQgWAHgIAGgAIiA6QgOgNAAgZIAAg6IgUAAIAAgIIA6hBIAFAAIAAArIAzAAIAAAeIgzAAIAAA3QABAKAFAGQAGAGAKAAQANAAAQgIIAAAgQgVAIgUAAQgZAAgOgNgAgHA0QgVgUAAggQAAgeAVgUQAUgUAjAAQAVAAAaAJIAAAgQgTgJgRAAQgTAAgNALQgLAKAAARQAAASALALQAMALATAAQANAAAZgJIAAAfQgZAJgVAAQglAAgUgTgAitA0QgWgUAAggQAAgeAVgUQAUgUAgAAQAgAAAUAVQAVAVgCAiIhjAAQABATANAKQAMALATAAQAZAAAbgUIAAAbQgZASglAAQgkAAgWgTgAiVgOIA8AAQgEgfgaAAQgbAAgDAfgAsXA0QgWgUAAggQAAgeAUgUQAVgUAgAAQAgAAAVAVQATAVAAAiIhkAAQABATAMAKQAMALAVAAQAYAAAbgUIAAAbQgZASgkAAQglAAgWgTgAr/gOIA8AAQgDgfgbAAQgbAAgDAfgAOHBFIAAhTQgBgbgVAAQgPAAgPAXIAABXIgsAAIAAiJIAsAAIAAAUQASgWAbAAQAVAAAPANQAOAOAAAaIAABWgAkNBFIAAiJIAsAAIAACJgAleBFIAAhPQABgPgIgIQgGgIgMAAQgTAAgPAXIAABXIgsAAIAAhQQAAgPgHgIQgHgHgMAAQgRAAgRATIAABbIgrAAIAAiJIArAAIAAASQAXgUAZAAQAkAAAPAdQAYgdAeAAQAYAAAPAOQAPAPAAAXIAABXgAt2BFIAAiJIArAAIAACJgAvHBFIAAhTQAAgbgWAAQgPAAgPAXIAABXIgrAAIAAiJIArAAIAAAUQATgWAaAAQAWAAAOANQAOAOAAAaIAABWgAPrAFQgDgCgDgJQgCgKAAgIQAAgRANgXQAKgRAAgIQAAgPgSAAQgOAAgLAKIgEAAIAIglQARgGASAAQAWAAAOAMQANALAAAUQABALgFALQgEAMgOASQgOASgEAJQgDAIAAAHIAAACQAAABAAABQAAAAgBABQAAABAAAAQAAAAgBAAIgHABQgGAAgCgCgANUhYIAXgsIAxAAIgxAsgAAShYIAXgsIAxAAIgxAsgAkIhgQgHgHAAgKQAAgJAHgHQAHgIAKAAQAKAAAHAIQAHAHAAAJQAAAKgHAHQgHAIgKAAQgKAAgHgIgAtyhgQgHgHAAgKQAAgJAHgHQAHgIAKAAQAKAAAHAIQAHAHAAAJQAAAKgHAHQgHAIgKAAQgKAAgHgIg");
	this.shape.setTransform(342.2,18.3);

	this.addChild(this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(235.8,4.5,212.8,27.7);


(lib.txt11 = function() {
	this.initialize();

	// txt
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#464749").s().p("AOvBiQAWgDAAghIAAiCIAsAAIAACNQAAAcgPARQgOARgYADgABGBiQAWgDAAghIAAiCIAsAAIAACNQAAAcgPARQgOARgYADgAwZCHIAphZIg2hyIAuAAIAdBGIAfhGIAuAAIhdDLgAguBuQAOgNAAgVIAAgFQgQgFAAgQQAAgLAHgGQAHgHALAAQANAAAJAJQAGAKAAAPQAAAWgNARQgPASgXACgAVOA6QgOgNAAgZIAAg6IgUAAIAAgIIA6hBIAFAAIAAArIAzAAIAAAeIgzAAIAAA3QAAAKAGAGQAFAGAKAAQAOAAAQgIIAAAgQgVAIgUAAQgZAAgOgNgAS2A9IAAgeQAbALASAAQAVAAAAgKQAAgEgEgDQgEgEgWgIQgWgJgIgJQgJgKAAgNQAAgTAQgMQAQgLAaAAQAYAAAUAKIAAAfQgZgQgVAAQgPAAAAALQAAADADADQADACAWAJQAWAJAJAJQAJAMAAANQAAAWgOAMQgPALgbAAQgcAAgWgKgAQkA0QgWgUAAggQAAgeAUgUQAVgUAgAAQAgAAAUAVQAUAVgBAiIhjAAQABATAMAKQAMALAUAAQAZAAAbgUIAAAbQgZASglAAQgkAAgWgTgAQ8gOIA8AAQgEgfgaAAQgbAAgDAfgALMAzQgWgUAAgfQAAgfAXgUQAWgTAiAAQAgAAAXATQAWATAAAgQAAAigXATQgXASgfAAQgjAAgWgUgALtghQgIAMAAAVQAAAuAgAAQAfAAAAguQAAgtgfAAQgPAAgJAMgAJXA6QgOgNAAgZIAAg6IgUAAIAAgIIA6hBIAGAAIAAArIAyAAIAAAeIgyAAIAAA3QAAAKAFAGQAGAGAKAAQANAAAQgIIAAAgQgVAIgTAAQgaAAgOgNgAD4A4QgXAPgXAAQgQAAgLgKQgLgKAAgNQAAgTALgLQAMgJA7gRQABgXgZAAQgcAAgXAXIAAgkQAbgQAhAAQA6AAAAAqIAAA9QAAAJAIAAQAFAAALgHIAAAYQgWAMgTAAQgUAAgEgPgADYAPQgIAGAAAKQAAAGAEAEQAEAFAGAAQAMAAAMgLIAAghQgWAHgIAGgAlLA9IAAgeQAaALASAAQAWAAAAgKQAAgEgEgDQgEgEgWgIQgXgJgIgJQgIgKAAgNQAAgTAQgMQAPgLAaAAQAZAAAUAKIAAAfQgZgQgVAAQgQAAAAALQAAADADADQAEACAWAJQAWAJAJAJQAJAMAAANQAAAWgPAMQgPALgbAAQgcAAgVgKgAneA0QgWgUAAggQAAgeAVgUQAUgUAgAAQAgAAAVAVQAUAVgBAiIhkAAQACATAMAKQAMALAUAAQAYAAAbgUIAAAbQgZASgkAAQglAAgWgTgAnGgOIA8AAQgDgfgbAAQgbAAgDAfgAqiBHIgjhJIgjBJIgUAAIg/iLIAtAAIAdBLIAfhLIAaAAIAfBLIAdhLIAtAAIg/CLgA18ApQghgeAAgqQAAgsAigfQAigfA3AAQAsAAAeASIAAAuQglgVghAAQghAAgUASQgVARAAAbQAAAbAUAQQAVASAgAAQAQAAAOgEQAPgEAdgPIAAAtQgnAUgqAAQg2AAgggegAGuBFIg2hEIgBAAIAABEIgrAAIAAjLIArAAIAACGIABAAIA1hEIAzAAIg2BEIA5BFgAjUBFIBIhrIhBAAIAAgeICHAAIhGBrIBGAAIAAAegAo9BFIAAiJIArAAIAACJgAy+BFIBIhrIhBAAIAAgeICHAAIhGBrIBGAAIAAAegAPKhgQgHgHAAgKQAAgJAHgHQAHgIAKAAQAKAAAHAIQAHAHAAAJQAAAKgHAHQgHAIgKAAQgKAAgHgIgABhhgQgHgHAAgKQAAgJAHgHQAHgIAKAAQAKAAAHAIQAHAHAAAJQAAAKgHAHQgHAIgKAAQgKAAgHgIgAo5hgQgHgHAAgKQAAgJAHgHQAHgIAKAAQAKAAAHAIQAHAHAAAJQAAAKgHAHQgHAIgKAAQgKAAgHgIg");
	this.shape.setTransform(379.1,18.3);

	this.addChild(this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(235.3,4.5,287.7,27.7);


(lib.logomc = function() {
	this.initialize();

	// Warstwa 3
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#C70358").s().p("AvTDjIAAiOIUUAAIAABrIAYADQAXAAANgMQANgLAAgUQAAgQgKgLQgKgKgOAAIgMACIgIAOQAGgEAHAAQAMAAAGAIQAHAIAAAMQAAANgIAHQgIAIgMAAIgPgCIAAhgIDwAAIAABrIAPAAIAAhrIGGAAIAACOgAHBCyQAAAPAVACIAIgLQgJgBgDgFQgCgDAAgLIAAgYQgBgZgeAAIgLABIgLAQIAWgGIAKACQAGADAAAFQAAAIgYAFQgZAFAAARQAAAKAIAHQAIAHAMAAIAIgBIAKgNIgMADQgRAAgBgOQABgGAFgDIAbgJgAJRCWIAfAqIATAAIghgrIAbggIgPAAgAIWCEQAFAHAAANIAAAoIAPAAIAAgpQAAgTgEgGQgIgLgRAAQgOAAgJANIAAgLIgPAAIAABLIAPAAIAAguQAAgUARAAQALAAAEAGgAvTBMIAAkuICxAAIAMACQAOADAGAFQAOAIAFASQAHASgDAZIgcC+IAcAAIAXi2IBKCpIASARIBKi6IAUC2IAlAAIgcjXIguAAIAAABQAAAJgFALIg3CMIg+iSQgYg5grgLIgGgBIbWAAIAAEugAFqgUQABBDA5AAQARAAAMgGQAKgGAJgOIAAAWIAeAAIAAiXIgeAAIAABYQAAATgKALQgMAMgQAAQgUAAgKgOQgHgJgBgZIAAhSIgeAAgAjchaQgWAWAAAjQAAAhAaAXQAbAXApAAQAaAAAUgIIARgfIgBAAQgWARghAAQgdAAgRgRQgTgPAAgeIB5AAQABgggVgVQgVgWghAAQgmAAgXAXgALvgiIAABNIAfAAIAAhWQAAgigMgQQgOgTgiAAQgfAAgWAdQgSgdghAAQgQAAgMAHQgKAGgJAOIAAgWIgeAAIAACWIAeAAIAAhVQAAgwAlAAQARAAAKANQAMAPAAAZIAABQIAdAAIAAhTQAAgZAJgLQAIgOAVAAQAlAAAAA4gAElArIAeAAIAAiWIgeAAgADShMQAJANAAAbIAABPIAeAAIgBhsQgBgPgGgJQgHgLgPgGQgNgGgQAAQgbAAgTAaIAAgVIgfAAIAACWIAfAAIAAhdQAAgoAjAAQAWAAAJAOgAAmhMQAIANAAAbIAABPIAfAAIgBhsQgBgPgHgJQgHgLgPgGQgNgGgPAAQgaAAgSAaIAAgVIgfAAIAACWIAfAAIAAhdQAAgoAhAAQAVAAAKAOgAkyArIAeAAIAAjYIgeAAgAl+ArIAfAAIAAjYIgfAAgAnKArIAdAAIAAiWIgdAAgAEliiQgGAGABAIQgBAJAGAFQAGAGAIAAQAJAAAFgGQAGgFAAgJQAAgIgGgGQgFgFgJAAQgIAAgGAFgAnLiiQgHAGABAIQgBAJAHAFQAGAGAHAAQAJAAAFgGQAGgGAAgIQAAgIgGgGQgFgFgJAAQgIAAgFAFgAjNg5QADgPALgKQAMgJARAAQAkAAAGAig");
	this.shape.setTransform(97,22.5);

	// Warstwa 4
	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AvTDjIAAnFIenAAIAAE3IAAAAIAACOg");
	this.shape_1.setTransform(97,22.5);

	this.addChild(this.shape_1,this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-1,-0.2,196.1,45.5);


(lib.legal = function() {
	this.initialize();

	// Warstwa 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#505153").s().p("AEaAyIARgjIgTgmIALAAIAOAaIAMgaIALAAIgjBJgAgPAyIAPgjIgQghIAAABIgJAHIAAAjIgJAAIAAgcIgJAFIAAgGIAJgHIAAglIAJAAIAAAdIAJgHIAAADIAJAAIALAaIAOgaIAKAAIghBJgAiPAuQgGgEgBgHQAAgKANgEQgFgDAAgCQAAgBAAgBQAAAAAAgBQABAAAAgBQABAAAAgBQACgCAEAAQgLgFAAgKQAAgHAFgFQAHgEAKgBIAUAAIAAAIIgKAAIAEAGIABAFQAAAEgCABQgDAEgDADQgDABgJABQgFABAAAEQAAAAAAAAQAAABABAAQAAAAAAABQABAAAAABIAIABIALADIAFAEQADAEAAAFQABAHgHAEQgGAEgKAAQgLAAgGgEgAiJAdQgDACgBAEQABAIAOAAQAGAAAEgDQADgBAAgEQAAgEgEgCQgFgCgHAAQgFAAgDACgAiFgLQgDACgBAEQABAEADABQACACAFAAQAEAAACgCQADgBAAgEQAAgEgDgDQgCgCgEAAQgFAAgCADgAEAAWIgCgDIgBgDIgBgJIAAgVIgIAAIAAgBIASgSIAAAKIAQAAIAAAJIgQAAIAAAXQAAAIAHAAQAFAAAGgEIAAAJQgGAEgGAAQgHAAgFgEgAChAWQgFgDgDgGQgDgFAAgIQAAgJAGgHQAHgIAKAAQAKAAAGAIQAFAHAAAJIAAABIgiAAQAAAHAEAEQAFAFAHAAQAKAAAHgHIAAAKIgIAFQgEABgHAAQgIAAgFgEgACkgMQgDAEgBAFIAZAAQgBgFgDgEQgCgDgGAAQgGAAgDADgABGATQgHgIAAgKQAAgJAHgIQAIgHALAAQAMAAAHAIQAIAHAAAJQgBAKgHAIQgIAHgLAAQgLAAgIgHgABNgJQgEAFAAAFQAAAHAEAEQAFAFAHAAQAHgBAFgEQAFgFAAgGQgBgFgEgFQgFgEgHgBQgIABgEAEgAhbATQgIgIABgKQgBgJAIgIQAIgHALAAQAMAAAHAIQAIAHAAAJQgBAKgHAIQgIAHgLAAQgLAAgIgHgAhUgJQgFAFABAFQgBAHAFAEQAFAFAHAAQAHgBAFgEQAFgFgBgGQAAgFgEgFQgFgEgHgBQgIABgEAEgAi6AWQgFgDgEgGQgCgFAAgIQgBgJAHgHQAGgIAKAAQALAAAFAIQAGAHAAAJIAAABIgiAAQgBAHAFAEQAEAFAIAAQAJAAAIgHIAAAKIgIAFQgFABgGAAQgJAAgEgEgAi3gMQgDAEgBAFIAZAAQgBgFgDgEQgDgDgGAAQgFAAgDADgAkdATQgHgHAAgLQAAgKAHgHQAHgHALgBIAHABIAHADIAAALQgIgFgGAAQgGAAgEAFQgFAEAAAFQAAAIAFAEQAEAFAIAAQAGAAAHgEIAAAKQgHADgIAAQgLAAgHgHgAmDATIAAgNQAIAKAMABQAEAAAEgEQADgCAAgEQAAgHgJgFIgJgEQgIgFgCgEQgEgFAAgGQAAgJAGgFQAHgGAJAAQAJAAAJAGIAAALQgJgHgJgBQgGAAgDADQgDACAAAEQAAAEADACQACADAGAEIAIAEQAOAJgBALQAAAIgFAGQgGAGgKAAQgMAAgIgHgAFrAZIARgYIgRgYIAJAAIARAYIgRAYgADOAZIAAgwIAKAAIAAAMIAAgBQAHgMAHAAQAFABAHAFIgGAJQgEgFgFAAQgFAAgDAFQgEAEABAFIAAAZgAB/AZIAAgnIgHAAIAAgJIAHAAIAAgCQAAgMAFgGQAFgGAIAAIAHABIAAAJIgFgBQgGAAgCAEQgCADAAAIIAAACIAJAAIAAAJIgJAAIAAAngAj3AZIAagnIgZAAIAAgJIAqAAIgaAnIAaAAIAAAJgAlVAZIAagnIgYAAIAAgJIAqAAIgaAnIAaAAIAAAJgAhPghIAHgQIALAAIgMAQg");
	this.shape.setTransform(39.4,6.7);

	this.addChild(this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(0.5,1.6,77.9,10.1);


(lib.arrowdffdg = function() {
	this.initialize();

	// Warstwa 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("Ag2CAQgHAAgFgFQgGgGgBgHQABgHAFgGIBghhIhfhgQgGgFgBgIQABgIAGgFQAFgGAHAAQAIAAAGAGIBsBuIABABQAEAFAAAGIAAAAQABAHgGAFIhtBvQgFAGgHAAIgBgBg");
	this.shape.setTransform(-27.2,6.2);

	// Warstwa 2
	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("rgba(0,0,0,0.09)").s().p("Ag2CAQgHAAgFgFQgGgGgBgHQABgHAFgGIBghhIhfhgQgGgFgBgIQABgIAGgFQAFgGAHAAQAIAAAGAGIBsBuIABABQAEAFAAAGIAAAAQABAHgGAFIhtBvQgFAGgHAAIgBgBg");
	this.shape_1.setTransform(-26.3,6.8);

	this.addChild(this.shape_1,this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-34.6,-6.6,15.7,26.4);


(lib.call = function() {
	this.initialize();

	// Warstwa 1
	this.instance = new lib.c1();
	this.instance.setTransform(1423.3,150,1,1,0,0,180,475,150);

	this.instance_1 = new lib.c1();
	this.instance_1.setTransform(475,150,1,1,0,0,0,475,150);

	this.addChild(this.instance_1,this.instance);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(0,0,1898.3,300);


(lib.bttxt = function() {
	this.initialize();

	// Warstwa 1
	this.instance = new lib.TXTASDCV();
	this.instance.setTransform(-161.9,14.5,1,1,0,0,0,68.8,20);

	this.addChild(this.instance);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-227.7,5,118.1,27.7);


(lib.TXT = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// txt33
	this.instance = new lib.txt33();
	this.instance.setTransform(524.7,27.6,1,1,0,0,0,116.8,14.5);
	this.instance.alpha = 0.25;
	this.instance._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(169).to({_off:false},0).to({x:468.4,alpha:1},8).wait(87).to({x:446.3,alpha:0.219},5).wait(1));

	// txt32
	this.instance_1 = new lib.txt32();
	this.instance_1.setTransform(577.4,58.4,1,1,0,0,0,121,15.3);
	this.instance_1.alpha = 0.25;
	this.instance_1._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(169).to({_off:false},0).to({x:468.4,alpha:1},8).wait(87).to({x:412.3,alpha:0.219},5).wait(1));

	// txt31
	this.instance_2 = new lib.txt31();
	this.instance_2.setTransform(632.5,89.8,1,1,0,0,0,155.8,14.5);
	this.instance_2.alpha = 0.25;
	this.instance_2._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_2).wait(169).to({_off:false},0).to({x:468.3,alpha:1},8).wait(87).to({x:378.2,alpha:0.219},5).wait(1));

	// txt298
	this.instance_3 = new lib.txt298();
	this.instance_3.setTransform(775.3,76.8,1,1,0,0,0,200.5,11.6);
	this.instance_3.alpha = 0.25;
	this.instance_3._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_3).wait(69).to({_off:false},0).to({x:506.5,alpha:1},6).wait(87).to({x:326.5,alpha:0.25},6,cjs.Ease.get(0.5)).to({_off:true},1).wait(101));

	// txt297
	this.instance_4 = new lib.txt297();
	this.instance_4.setTransform(652.5,48.8,1,1,0,0,0,161.5,11.6);
	this.instance_4.alpha = 0.25;
	this.instance_4._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_4).wait(69).to({_off:false},0).to({x:483.8,alpha:1},6).wait(87).to({x:371.3,alpha:0.25},6,cjs.Ease.get(0.5)).to({_off:true},1).wait(101));

	// txt296
	this.instance_5 = new lib.txt296();
	this.instance_5.setTransform(571.3,19.8,1,1,0,0,0,140.3,11.6);
	this.instance_5.alpha = 0.25;
	this.instance_5._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_5).wait(69).to({_off:false},0).to({x:546.3,alpha:1},6).wait(87).to({x:478.8,alpha:0.25},6,cjs.Ease.get(0.5)).to({_off:true},1).wait(101));

	// txt12
	this.instance_6 = new lib.txt12();
	this.instance_6.setTransform(345.8,77.8,1,1,0,0,0,148.3,14.5);
	this.instance_6.alpha = 0.219;

	this.timeline.addTween(cjs.Tween.get(this.instance_6).to({x:274,alpha:1},5,cjs.Ease.get(0.5)).wait(59).to({x:154.6,alpha:0.16},4,cjs.Ease.get(0.5)).to({_off:true},1).wait(201));

	// txt11
	this.instance_7 = new lib.txt11();
	this.instance_7.setTransform(271.5,41.8,1,1,0,0,0,155.8,14.5);
	this.instance_7.alpha = 0.219;

	this.timeline.addTween(cjs.Tween.get(this.instance_7).to({x:244.6,alpha:1},5,cjs.Ease.get(0.5)).wait(59).to({x:101.9,alpha:0.16},4,cjs.Ease.get(0.5)).to({_off:true},1).wait(201));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(350.9,31.7,295.2,63.6);


(lib.img12_1 = function() {
	this.initialize();

	// Warstwa 2
	this.instance = new lib.logo100();
	this.instance.setTransform(38,27.7,0.565,0.565,0,0,0,73,59.9);

	this.addChild(this.instance);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-1.9,-3.7,80.4,64);


(lib.Ellipse3 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Warstwa 3
	this.instance = new lib.circ1();
	this.instance.setTransform(60.4,61.3,1,1,0,0,0,51.8,51.8);

	this.timeline.addTween(cjs.Tween.get(this.instance).to({scaleX:0.98,scaleY:0.98},36,cjs.Ease.get(0.5)).to({scaleX:1,scaleY:1},28,cjs.Ease.get(0.5)).wait(1));

	// Warstwa 2
	this.instance_1 = new lib.circ1();
	this.instance_1.setTransform(60.4,61.3,1.172,1.172,0,0,0,51.8,51.8);
	this.instance_1.alpha = 0.199;

	this.timeline.addTween(cjs.Tween.get(this.instance_1).to({scaleX:1.26,scaleY:1.26,alpha:0.398},22,cjs.Ease.get(0.5)).to({scaleX:1.17,scaleY:1.17,alpha:0.199},42,cjs.Ease.get(0.5)).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-0.3,0.6,121.4,121.4);


(lib.Ellipse2 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Warstwa 3
	this.instance = new lib.circ1();
	this.instance.setTransform(60.4,61.3,1,1,0,0,0,51.8,51.8);

	this.timeline.addTween(cjs.Tween.get(this.instance).to({scaleX:0.98,scaleY:0.98},26,cjs.Ease.get(0.5)).to({scaleX:1,scaleY:1},23,cjs.Ease.get(0.5)).wait(1));

	// Warstwa 2
	this.instance_1 = new lib.circ1();
	this.instance_1.setTransform(60.4,61.3,1.172,1.172,0,0,0,51.8,51.8);
	this.instance_1.alpha = 0.199;

	this.timeline.addTween(cjs.Tween.get(this.instance_1).to({scaleX:1.26,scaleY:1.26,alpha:0.398},26,cjs.Ease.get(0.5)).to({scaleX:1.17,scaleY:1.17,alpha:0.199},23,cjs.Ease.get(0.5)).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-0.3,0.6,121.4,121.4);


(lib.Ellipse1copy = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Warstwa 3
	this.instance = new lib.circ1();
	this.instance.setTransform(60.4,61.3,1,1,0,0,0,51.8,51.8);

	this.timeline.addTween(cjs.Tween.get(this.instance).to({scaleX:0.98,scaleY:0.98},17,cjs.Ease.get(0.5)).to({scaleX:1,scaleY:1},12,cjs.Ease.get(0.5)).wait(1));

	// Warstwa 2
	this.instance_1 = new lib.circ1();
	this.instance_1.setTransform(60.4,61.3,1.172,1.172,0,0,0,51.8,51.8);
	this.instance_1.alpha = 0.199;

	this.timeline.addTween(cjs.Tween.get(this.instance_1).to({scaleX:1.26,scaleY:1.26,alpha:0.398},13,cjs.Ease.get(0.5)).to({scaleX:1.17,scaleY:1.17,alpha:0.199},16,cjs.Ease.get(0.5)).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-0.3,0.6,121.4,121.4);


(lib.KULA31 = function() {
	this.initialize();

	// txt35
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#505153").s().p("ADcA3IgFgGIgDgIIgBgTIAAgsIgSAAIAAgCIAmgmIAAAWIAhAAIAAASIghAAIAAAxQAAASAPAAQALAAAMgHIAAATQgLAGgOAAQgOAAgKgIgABzA4QgLgIgGgLQgGgNAAgPQAAgWANgPQANgPAWAAQAVAAALAPQANAOAAAWIAAADIhJAAQAAAPAKAJQAJAJAPAAQAUAAARgNIAAAUQgJAGgJADQgKADgNAAQgQAAgLgHgAB6gTQgHAHgDAMIA1AAQgBgMgHgHQgGgFgLAAQgLAAgHAFgAAjA/IgfhGIgcBGIgHAAIguhnIAWAAIAbA8IAbg8IANAAIAaA8IAbg8IAWAAIguBngAhsA0QgNALgPAAQgLAAgGgHQgIgIAAgKQAAgKAIgIQAGgIANgEIAagIIAAgFQAAgSgSAAQgRAAgQARIAAgWQAMgPAXAAQAQAAAKAJQAEADACAFQAEAEAAAFIABARIAAArQAAAFAEAAQADAAAIgFIAAAMIgLAHIgJABQgNAAgDgLgAh5APQgLAEgEAFQgFAEAAAGQAAAHAFAEQAEADAHAAQAJAAAIgHIAAgfgAjKA9IAAg6QAAgPgEgHQgFgGgLAAQgPAAgKAPIAABHIgVAAIAAhlIAVAAIAAAMQAOgPARAAQAKAAAIAFQAIAFAFAJQAEAJAAARIAAA7g");
	this.shape.setTransform(860.1,49.7);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#C82059").s().p("AgmBaQgVghAAg5QAAg5AWggQAWghAkAAQAlAAAWAiQAVAfAAA5QAAA5gVAhQgUAggmAAQgmAAgWgggAAAg8QgGAQAAAuQAAAoAGARQAGATAPgBQAOAAAGgRQAHgRAAgvQAAgngHgRQgGgRgPAAQgOAAgGARgAjUBjQgXgYAAgmQABgnAgg0IAphEIA7AAIg3BaIAQgBQAaAAAUAUQASAUABAhQAAAkgXAXQgWAXgjAAQgjABgVgYgAiuAQQgIAJAAASQAAAPAIAKQAGAKANgBQANAAAHgKQAHgJAAgRQAAgQgHgJQgIgKgMAAQgNAAgGAKgAmVBtIAAguQAbASAXAAQARAAAKgJQALgJAAgOQAAgOgKgJQgLgJgQgBIAAgoQAOAAAJgJQAJgIAAgMQAAgMgKgHQgJgIgOAAQgVAAgXALIAAgqQAXgLAfAAQAjAAAUARQAWARgBAZQAAAkgiATQApAPAAAtQAAAfgXAUQgYATglAAQghAAgagNgAFIB3IAAhUIgbAXIAAgpIAbgVIAAhzIAyAAIAABPIAcgWIAAAoIgcAWIAAB3gACUB3IBSh9IhKAAIAAgjICdAAIhTB9IBTAAIAAAjg");
	this.shape_1.setTransform(861.6,77.2);

	// circl2
	this.instance = new lib.Ellipse1copy();
	this.instance.setTransform(859.7,69.2,1.133,1.133,0,0,0,60.5,60.5);

	this.addChild(this.instance,this.shape_1,this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(790.8,1.3,137.5,137.5);


(lib.KULA24 = function() {
	this.initialize();

	// txt292
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#47484A").s().p("ADsCRQgCgDAAgFQAAgEADgFQgCgBgBgDQgGAGgHAAQgFAAgDgFQgEgDAAgFQAAgEADgDQACgDADgCIARgGIAAgDQAAgIgIAAQgJAAgHAIIAAgLQAGgGAKAAQAFAAAEABQAEADACADQACAEAAAJIAAAVQAAAAAAABQAAAAABABQAAAAAAAAQABAAAAAAIAGgCIAAAFIgHAEQgCADAAADIABADQABABAAAAQAAABABAAQAAAAABAAQAAAAABAAIAFgBIAAAHQgDABgEAAQgFAAgEgCgADgBtIgEADQAAAAAAABQgBAAAAAAQAAABAAABQAAAAAAABQAAAAAAABQAAABAAAAQAAABABAAQAAABABAAQACADADAAQAEAAAEgFIAAgOIgKAFgABHB7QgHgHAAgMQAAgLAHgHQAGgHALAAIAHAAIAHADIAAALQgHgFgGAAQgHAAgEAFQgEAEAAAHQAAAIAEAEQAFAEAHAAQAGAAAHgDIAAAKQgHACgHAAQgLAAgHgGgAhpB7QgHgHAAgMQAAgLAGgHQAHgHAKAAIAHAAIAHADIAAALQgHgFgGAAQgGAAgEAFQgFAEAAAHQAAAIAFAEQAEAEAIAAQAFAAAHgDIAAAKQgHACgGAAQgMAAgGgGgAiZB9QgFgCgDgGQgDgGAAgHQAAgLAHgHQAGgHAKAAQAJAAAGAHQAGAGAAAMIAAABIgiAAQAAAHAEAEQAFAEAGAAQAKAAAIgGIAAAKQgFADgEABQgEABgGAAQgIAAgFgEgAiWBaQgDADgBAGIAYAAQAAgGgDgDQgDgDgFAAQgFAAgEADgAi/B9IgCgCIgCgEIgBgJIAAgVIgIAAIAAgCIASgRIAAAKIAPAAIAAAJIgPAAIAAAXQAAAIAHAAQAFAAAGgDIAAAJQgFADgHAAQgHAAgEgEgAC+CAIAAgbQAAgIgCgDQgCgDgGAAQgHAAgEAHIAAAiIgKAAIAAgwIAKAAIAAAGQAGgHAIAAQAFAAAEACQADADADAEQACAEAAAJIAAAbgABsCAIAagnIgYAAIAAgJIApAAIgaAnIAaAAIAAAJgAAsCAIAAgwIAJAAIAAAwgAAVCAIAAgbQAAgIgDgDQgCgDgGAAQgGAAgEAHIAAAiIgJAAIAAgwIAJAAIAAAGQAFgHAJAAQAEAAAEACQAEADACAEQACAEAAAJIAAAbgAggCAIAAgeQAAgFgDgDQgCgEgEAAQgDAAgDACQgDACgDAEIAAAiIgKAAIAAhJIAKAAIAAAfQAGgHAIAAQAFAAAFACQADADACAEQACAEAAAJIAAAbgAj7CAIAAgwIAKAAIAAAwgAAsBFIgBgEQAAAAAAgBQAAgBAAAAQAAgBABAAQAAAAAAgBQABAAAAgBQABAAAAAAQABAAAAgBQABAAAAAAQABAAAAAAQABAAABABQAAAAAAAAQABAAAAABQABAAAAABQAAAAABABQAAAAAAABQAAABAAAAQAAABAAAAQAAABAAAAQgBABAAAAQAAABgBAAQAAABgBAAQAAAAAAAAQgBABgBAAQAAAAgBAAIgEgCgAj6BFIgBgEQAAAAAAgBQAAgBAAAAQAAgBABAAQAAAAAAgBQABAAAAgBQAAAAABAAQAAAAABgBQABAAAAAAQABAAAAAAQABAAABABQAAAAAAAAQABAAAAABQABAAAAABQAAAAAAABQABAAAAABQAAABAAAAIgCAEQAAABgBAAQAAAAAAAAQgBABgBAAQAAAAgBAAQAAAAgBAAQgBAAAAgBQgBAAAAAAQAAAAgBgBgAgYArIAQgjIgSgkIALAAIANAbIAKgbIALAAIggBHgADDAjQgDgDAAgFQAAgEADgFQAAAAgBgBQAAAAAAAAQgBgBAAgBQAAAAAAgBQgHAFgHAAQgFAAgDgEQgEgDAAgFQAAgEADgDIAGgDIARgGIAAgDQAAgIgJAAQgIAAgIAIIAAgLQAGgHALAAQAFAAAEACIAGAGQACAEAAAJIAAASQAAABAAABQAAAAAAAAQAAABABAAQAAAAABAAIAFgDIAAAGIgHAEQgCADAAADIABADQABABAAAAQABAAAAAAQABABAAAAQABAAAAAAIAGgBIAAAHQgEACgEAAQgFAAgDgDgAC2AAIgDACQgBAAAAABQgBAAAAAAQAAABAAAAQAAABAAAAQAAAEACABQABABAAAAQABAAAAABQABAAABAAQAAAAABAAQAFAAAEgDIAAgNIgLAEgAAeAMQgHgHAAgJQAAgLAGgHQAHgIALAAIAHABIAHADIAAAKQgHgEgHAAQgGAAgEAEQgEAFAAAHQAAAFAEAFQAEAEAIAAQAGAAAHgDIAAAJQgHADgHAAQgMAAgGgHgAh1APQgGgDgDgFQgCgGAAgFQAAgMAGgHQAGgHAKAAQAJAAAGAHQAGAHAAALIAAACIgiAAQAAAFAEAEQAFAEAGAAQAKAAAIgGIAAAKIgIAEQgFABgGAAQgIAAgEgEgAhzgSQgDADgBAGIAZAAQgBgGgDgDQgDgDgFAAQgFAAgEADgACVASIAAgZQAAgIgCgDQgDgDgFAAQgHAAgFAHIAAAgIgJAAIAAguIAJAAIAAAGQAHgIAIAAQAFAAADADQAEADACAEQADAEAAAIIAAAagABDASIAaglIgZAAIAAgJIAqAAIgaAlIAaAAIAAAJgAg1ASQgLAAgGgHQgHgHAAgJQAAgLAHgHQAHgHAKAAQAFAAAGADIAAgaIAJAAIAABHgAg/gQQgEAEAAAIQAAAGAEAEIAEADIAJABIAIAAIAAgcQgEgDgGAAQgGAAgFAFgAiVASIAAgbQAAgFgDgEQgCgDgFAAQgGAAgFAGIAAAhIgJAAIAAgZQAAgIgDgDQgCgDgFAAQgDAAgDABIgGAFIAAAhIgJAAIAAguIAJAAIAAAGQAIgIAHAAQAJAAAFAKQAIgKAIAAQAHAAAFAGQAFAFAAALIAAAagAhXhIIAAhJIARAAQANAAAHAGQAIAGAAAMQAAALgHAHQgHAHgLAAQgEAAgGgCIAAAagAhNhqQAEABAFAAQAHAAAEgEQAFgFAAgHQAAgFgCgDQgCgEgEgBQgDgCgHAAIgHAAgACshnQgHgHAAgLQAAgLAHgHQAGgHALAAIAHABQADAAAEACIAAAKQgHgEgGAAQgHAAgEAEQgEAFAAAHQAAAHAEAFQAFAEAIAAQAFAAAHgDIAAAJQgHADgHAAQgLAAgHgHgABxhnQgHgHAAgLQAAgKAHgIQAHgGALAAQALAAAIAGQAHAIAAALQAAAKgHAHQgIAHgLAAQgLAAgHgHgAB4iEQgFAEAAAHQAAAHAFAFQAFAEAGAAQAHAAAFgFQAFgEAAgHQAAgHgFgEQgFgFgHAAQgHAAgEAFgAgchnQgHgHAAgLQAAgKAHgIQAIgGALAAQAJAAAHAGQAIAIAAALQAAAKgIAHQgHAHgKAAQgLAAgHgHgAgViEQgEAEAAAHQAAAHAEAFQAEAEAIAAQAHAAACgFQAEgEAAgHQAAgHgEgEQgDgFgHAAQgHAAgEAFgAiNhlQgGAFgHAAQgFAAgDgDQgEgEAAgFQAAgEAEgEQADgEAGgCIAMgEIAAgCQAAgJgJAAQgHAAgIAIIAAgLQAFgGALAAQAIAAAEAEIAEADIABAFIAAAIIAAAVQAAAAAAABQAAAAABAAQAAABAAAAQABAAAAAAIAGgCIAAAGIgGACIgEABQgGAAgBgFgAiUh2IgHAEQAAAAAAABQgBAAAAABQAAAAAAABQAAABAAAAQAAAEABABQACACADAAQAFAAAEgDIAAgPgABVhhIAAgdQAAgGgCgDQgCgDgFAAQgGAAgFAGIAAAjIgKAAIAAgbQAAgIgCgDQgCgEgGAAIgFACIgGAFIAAAjIgJAAIAAgwIAJAAIAAAGQAIgHAHAAQAJAAAFAJQAIgJAIAAQAHAAAEAFQAFAFAAALIAAAcgAjUhhIAZgnIgYAAIAAgJIApAAIgaAnIAaAAIAAAJg");
	this.shape.setTransform(-62.6,141.3);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#C82059").s().p("AiaBCQgQgYAAgqQAAgqAQgYQARgYAcAAQAcAAAQAYQAQAYAAAqQAAAqgQAYQgPAZgdAAQgdAAgQgZgAh9gsQgFALAAAiQAAAfAFANQAFANALgBQALABAFgNQAEgNAAgjQAAgdgEgMQgFgMgLgBQgLABgFAMgABxBZIAAg/IgVARIAAgeIAVgPIAAhVIAlAAIAAA5IAVgQIAAAfIgVAPIAABZgAghBZIA9hdIg3AAIAAgaIB0AAIg9BdIA9AAIAAAag");
	this.shape_1.setTransform(-62.2,107.3);

	// podb1
	this.instance = new lib.separacja();
	this.instance.setTransform(-62.7,121.6,0.595,0.688,0,0,0,38.3,0.5);

	// Warstwa 9
	this.instance_1 = new lib.Ellipse3();
	this.instance_1.setTransform(-62.4,128.3,0.771,0.771,0,0,0,60.5,60.5);

	this.instance_2 = new lib.separacja();
	this.instance_2.setTransform(-62.9,121.7,0.601,0.765,0,0,0,38.4,0.5);

	this.addChild(this.instance_2,this.instance_1,this.instance,this.shape_1,this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-109.4,82.1,93.6,93.6);


(lib.KULA23 = function() {
	this.initialize();

	// Rectangle 1
	this.instance = new lib.separacja();
	this.instance.setTransform(20.1,-43.7,0.641,0.816,0,0,0,38.3,0.5);

	// txt291
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#47484A").s().p("ADFCbQgFgEAAgIQAAgGAFgHIgCAAIgCAAQgRAAgLgLQgLgMAAgSQAAgSAKgMQAKgKARgBQAPABAJAKQAKALgBATIAAACIg3AAQABAKAHAIQAHAGALAAQAQAAAMgKIAAAQIgLAGQgGAHgBAFQAAADADADQADACADAAQAEAAAEgBIAAALQgFACgGAAQgIABgGgFgACqBSIAnAAQgBgUgRAAQgSAAgDAUgABuB7IgEgEIgDgGIAAgOIAAgjIgOAAIAAgBIAdgdIAAAQIAZAAIAAAOIgZAAIAAAmQAAAOALAAQAJAAAJgGIAAAPQgJAFgKAAQgMAAgGgHgAgMB6QgJAHgLAAQgJAAgFgEQgGgGABgJQgBgHAGgFQAGgHAJgDIAUgGIAAgFQAAgOgPAAQgMAAgMANIAAgRQAJgKARgBQAMAAAJAIIADAFIACAHIAAAOIAAAgQAAAFADAAQADAAAFgFIAAAKIgIAEQgDACgCAAQgJAAgDgIgAgVBeQgJADgCADQgEAEAAAEQAAAFADADQADADAFAAQAIAAAGgGIAAgXgAAdCAIAAhOIAPAAIAAASIABgBQALgTALAAQAJAAAKAJIgJAOQgHgHgIAAQgHgBgFAIQgGAHAAAJIAAApgAhJCAIgngnIAjgnIASAAIghAnIAoAngAiACAIAAh2IAQAAIAAB2gAjWCAIAAhOIAPAAIAABOgAjVAhQgDgDAAgDQAAgEADgDQADgDADAAQAEAAADADQACADAAAEQAAADgCADQgDADgEAAQgDAAgDgDgADlgyQgMgLAAgRQAAgRAMgLQAMgMASAAQASAAAMAMQALALABASQgBAQgLALQgMAMgTAAQgSAAgLgMgADvhgQgGAGgBAMQAAALAIAIQAHAGALABQAMAAAHgIQAIgHgBgLQAAgMgHgGQgHgIgMAAQgLAAgIAIgACtgsIgEgFIgCgGIgBgOIAAgjIgOAAIAAgBIAegdIAAAQIAYAAIAAAOIgYAAIAAAmQAAAOALAAQAIAAAKgGIAAAPQgKAFgKAAQgLAAgHgGgAgKgyQgMgLAAgRQAAgRAMgLQAKgMASAAQARAAANAMQAMALgBASQABAQgMALQgNAMgSAAQgRAAgKgMgAAAhgQgGAGAAAMQgBALAHAIQAGAGALABQAMAAAIgIQAGgHAAgLQABgMgIgGQgIgIgLAAQgLAAgGAIgAi4guQgKAHgMAAQgHAAgGgEQgGgGAAgJQAAgGAGgGQAFgHAKgDIAUgGIAAgFQAAgOgPAAQgMAAgMANIAAgRQAJgKARgBQAMAAAJAHIAEAGIACAHIABAOIAAAhQAAABAAAAQAAABABABQAAAAABAAQAAAAABAAQADAAAGgDIAAAJIgJAEQgDACgEAAQgKAAgBgIgAjChKQgIADgEADQgDAEAAAEQAAAFADADQADADAFAAQAHAAAHgGIAAgXgAB/goIAAgsQgBgMgEgFQgDgGgIABQgLAAgIALIAAA3IgQAAIAAhOIAQAAIAAAKQAKgMANAAQAIAAAGAFQAHADADAHQADAHAAANIAAAtgAgogoIgognIAjgnIASAAIggAnIAnAngAhfgoIAAh2IAPAAIAAB2gAksgoIAqhAIgoAAIAAgOIBDAAIgqBAIAqAAIAAAOg");
	this.shape.setTransform(20.1,-28,0.816,0.816);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#C82059").s().p("AjHBWQgUgfAAg3QAAg3AVgeQAVggAkAAQAkABAVAfQAUAfAAA2QAAA2gUAgQgUAggkgBQgmABgVgggAiig5QgGAPAAAsQAAAmAGASQAHARAOAAQAOAAAGgRQAGgRAAgsQAAgngGgPQgGgRgOABQgOgBgHARgACRByIAAhQIgaAVIAAgnIAagTIAAhvIAxAAIAABMIAagWIAAAoIgaAUIAABygAgqByIBNh4IhGAAIAAghICWAAIhQB4IBQAAIAAAhg");
	this.shape_1.setTransform(21,-58.1,0.816,0.816);

	// Warstwa 7
	this.instance_1 = new lib.Ellipse1copy();
	this.instance_1.setTransform(21.7,-44.2,0.737,0.737,0,0,0,60.5,60.5);

	this.addChild(this.instance_1,this.shape_1,this.shape,this.instance);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-23.1,-88.4,89.5,89.5);


(lib.KULA22 = function() {
	this.initialize();

	// separator
	this.instance = new lib.separacja();
	this.instance.setTransform(-117.1,50.2,0.704,0.813,0,0,0,38.4,0.5);

	// TXT26
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#C82059").s().p("Ai2BPQgTgcAAgzQAAgyAUgcQATgdAhABQAhAAATAcQATAdAAAxQAAAygSAdQgTAcgiABQgigBgTgcgAiUg0QgGAOAAAnQAAAlAGAPQAGAQANAAQANAAAFgQQAGgPAAgpQAAgjgGgOQgFgPgOAAQgMAAgGAPgACFBpIAAhKIgYAUIAAgkIAYgSIAAhlIAtAAIAABGIAYgUIAAAkIgYASIAABpgAgmBpIBHhuIhBAAIAAgeICJAAIhIBtIBIAAIAAAfg");
	this.shape.setTransform(-115.9,33.7);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#47484A").s().p("AFcBsIgSgnIgQAnIgEAAIgZg6IAMAAIAPAjIAOgjIAJAAIAOAjIAPgjIAMAAIgZA6gADkBkQgJgIAAgMQAAgNAJgIQAJgJANAAQAMAAAJAJQAJAIAAANQAAAMgJAIQgJAIgNAAQgNAAgIgIgADsBCQgFAFAAAJQAAAIAFAFQAFAFAJAAQAIAAAFgFQAFgGAAgIQAAgIgFgFQgGgGgIAAQgIAAgFAGgAC7BoIgDgDIgCgFQgBgCAAgIIAAgaIgKAAIAAgBIAWgUIAAALIASAAIAAAKIgSAAIAAAdQAAAJAIAAQAGAAAHgEIAAALQgHADgHAAQgIAAgFgEgACWBnQgHAFgIAAQgGAAgEgEQgEgDAAgGQAAgGAEgEQAEgEAHgDIAOgFIAAgDQAAgLgKAAQgJAAgJALIAAgNQAGgIANAAQAJAAAGAFIADAEIACAFIAAAKIAAAYQAAABAAABQABAAAAABQAAAAABAAQAAAAABAAIAGgDIAAAHIgGAEIgFAAQgHAAgCgFgACPBSQgGACgDADQgCACAAAEQAAADACACQADADADAAQAGAAAEgFIAAgRgAgkBkQgIgIAAgMQAAgNAIgIQAJgJANAAQANAAAGAJQAKAIAAANQAAAMgKAIQgGAIgNAAQgNAAgJgIgAgcBCQgFAFAAAJQAAAIAFAFQAFAFAJAAQAIAAAGgFQADgGAAgIQAAgIgDgFQgGgGgIAAQgJAAgFAGgAjABnQgHAFgIAAQgGAAgEgEQgEgDAAgGQAAgGAEgEQAEgEAHgDIAOgFIAAgDQAAgLgKAAQgJAAgJALIAAgNQAGgIANAAQAJAAAGAFIADAEIACAFIAAAKIAAAYQAAABAAABQAAAAABABQAAAAAAAAQABAAAAAAQACAAAFgDIAAAHIgGAEIgFAAQgHAAgCgFgAjHBSQgGACgDADQgCACAAAEQAAADACACQACADAEAAQAGAAAEgFIAAgRgAkPBsQgGgBgEgDIAAhTIALAAIAAAhQAHgFAJAAQALAAAHAIQAHAIAAANQAAAOgJAIQgIAIgOAAIgLAAgAkOBBIAAAfIANACQAHAAAFgFQAFgGAAgIQAAgJgFgFQgFgGgHAAQgGAAgHAGgABiBsIAAgjQAAgHgCgDQgDgEgGAAQgHAAgGAHIAAAqIgMAAIAAggQAAgKgCgDQgCgEgHAAIgGABIgHAGIAAAqIgLAAIAAg6IALAAIAAAIQAJgJAIAAQALAAAGAKQAJgKAKAAQAIAAAFAGQAFAGAAANIAAAigAg6BsIgdgeIAagcIANAAIgZAcIAeAegAhiBsIAAhXIALAAIAABXgAh+BsIAAghQAAgJgCgDQgDgEgHAAQgIAAgFAHIAAAqIgMAAIAAg6IAMAAIAAAIQAHgJAKAAQAGAAAEADQAFADACAEQACAGAAAKIAAAhgAl3BsIAegvIgdAAIAAgLIAxAAIgfAvIAfAAIAAALgADxAmIAJgTIAMAAIgOATgADVAHIATgoIgWgtIANAAIAPAhIAPghIANAAIgpBVgAAdAHIAAhVIAUAAQAPAAAIAIQAJAHAAAOQAAANgJAIQgHAJgNAAQgFAAgHgDIAAAdgAAoggQAFACAGAAQAIAAAFgFQAFgFAAgJQAAgGgCgEQgCgEgFgCQgEgCgIAAIgIAAgAgeAHIAUgoIgWgsIgZA6IgEAAIgRgpIgQApIgEAAIgag7IANAAIAOAjIAPgjIAIAAIAPAjIAPgjIAZAAIAPAhIANghIANAAIgnBVgAC2gYIgCgDIgCgEIgBgLIAAgaIgKAAIAAgBIAVgVIAAAMIATAAIAAAKIgTAAIAAAcQAAAKAJAAQAGAAAHgEIAAALQgHAEgIAAQgHAAgGgFgACSgZQgHAGgJAAQgGAAgEgFQgEgDAAgGQAAgGAEgEQAEgEAHgDIAPgFIAAgDQAAgKgLAAQgIAAgKAJIAAgMQAHgIANAAQAJAAAFAFIAEAEIACAFIAAAKIAAAYQAAABAAABQAAAAAAAAQAAABABAAQAAAAABAAQACAAAEgDIAAAHIgGAEIgFABQgHAAgBgGgACKguIgIAFQgDACAAADQAAAEADACQACADAEAAQAFAAAFgFIAAgRgAi1gZQgHAGgIAAQgGAAgEgFQgEgDAAgGQAAgGAEgEQAEgEAHgDIAOgFIAAgDQAAgKgKAAQgJAAgJAJIAAgMQAHgIAMAAQAJAAAGAFIADAEIACAFIAAAKIAAAYQAAABAAABQAAAAABAAQAAABAAAAQABAAAAAAQADAAAEgDIAAAHIgGAEIgFABQgHAAgCgGgAi9guIgHAFQgDACAAADQAAAEADACQABADAEAAQAGAAAEgFIAAgRgABegUIAAgjIgKAIIAAgKIAKgIIAAgqIALAAIAAAhIAKgIIAAAKIgKAJIAAArgAkJgUIAegvIgdAAIAAgLIAxAAIgfAvIAfAAIAAALg");
	this.shape_1.setTransform(-116.7,64.7);

	// Warstwa 7
	this.instance_1 = new lib.Ellipse2();
	this.instance_1.setTransform(-115.4,55.3,0.898,0.898,0,0,0,60.5,60.5);

	this.addChild(this.instance_1,this.shape_1,this.shape,this.instance);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-170.1,1.5,109,109);


(lib.KULA21 = function() {
	this.initialize();

	// Rectangle 1
	this.instance = new lib.separacja();
	this.instance.setTransform(115.4,84.2,0.762,0.762,0,0,0,38.4,0.4);

	// txt22
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#47484A").s().p("AC4EWIgCgDIgDgEIgBgLIAAgbIgKAAIAAgBIAXgVIAAAMIASAAIAAAKIgSAAIAAAdQgBAKAJAAQAGAAAHgEIAAALQgGAEgJAAQgHAAgGgFgAB8EXQgGgEgDgHQgEgHAAgJQAAgOAIgIQAHgIAMAAQAMAAAHAIQAHAIAAAOIAAABIgpAAQAAAJAFAFQAGAFAHAAQAMAAAKgHIAAALQgFAEgGABQgFACgHAAQgJAAgHgEgACADsQgEADgBAHIAdAAQAAgHgDgDQgEgEgHAAQgGAAgEAEgAg1EXQgHgEgDgHQgDgHAAgJQAAgOAHgIQAIgIAMAAQALAAAIAIQAGAIABAOIAAABIgqAAQAAAJAGAFQAFAFAIAAQAMAAAKgHIAAALQgGAEgFABQgGACgHAAQgKAAgFgEgAgxDsQgFADgBAHIAeAAQgBgHgDgDQgEgEgGAAQgHAAgDAEgAhkEWIgDgDIgCgEIgBgLIAAgbIgKAAIAAgBIAWgVIAAAMIATAAIAAAKIgTAAIAAAdQAAAKAJAAQAGAAAGgEIAAALQgGAEgIAAQgIAAgFgFgABXEaIAAgiQgBgJgCgDQgDgFgGAAQgJAAgGAJIAAAqIgLAAIAAg7IALAAIAAAIQAIgJAKAAQAFAAAFADQAFADACAFQADAFAAAKIAAAigAAAEaIAAg7IAJAAIAAANIABAAQAJgOAIAAQAGAAAIAGIgHALQgGgGgEAAQgGAAgEAFQgFAGAAAHIAAAfgAiIEaIAAgiQAAgJgCgDQgDgFgGAAQgJAAgGAJIAAAqIgLAAIAAg7IALAAIAAAIQAIgJAKAAQAFAAAFADQAFADADAFQACAFAAAKIAAAigAjJEaIAAg7IALAAIAAA7gAjIDSQgCgCAAgDQAAgDACgCQACgCACAAQAEAAACACQABACAAADQAAADgBACQgCACgEAAQAAAAgBAAQAAAAgBgBQAAAAgBAAQgBAAAAgBgACICZIAAhZIAVAAQAPAAAJAIQAJAIgBAOQABANgJAJQgIAIgNAAQgFAAgHgCIAAAfgACUBvQAGADAFAAQAIAAAGgFQAFgGAAgJQAAgGgCgEQgDgFgFgCQgDgCgJAAIgIAAgAhTCZIAUgqIgWgvIAMAAIARAiIAPgiIAMAAIgpBZgAE/B4QgGgEgDgHQgFgHAAgIQAAgOAIgJQAHgIANAAQAMAAAGAIQAIAIgBAOIAAACIgoAAQAAAIAFAFQAGAFAHAAQAMAAAJgHIAAALQgFAEgFABQgGACgGAAQgKAAgGgEgAFDBNQgFAEAAAHIAdAAQgBgHgDgEQgEgEgGAAQgHAAgDAEgAgPB0QgJgIABgOQAAgOAHgIQAJgJALAAIAIABIAJADIAAANQgJgGgIAAQgGAAgFAGQgFAFAAAJQAAAJAFAFQAGAFAHAAQAIAAAIgEIAAAMQgJADgIAAQgMAAgIgIgAhxB3QgBAAAAAAQgBgBAAAAQAAAAgBgBQAAAAAAgBIgDgEIAAgLIAAgaIgKAAIAAgCIAVgVIAAAMIATAAIAAALIgTAAIAAAdQAAAKAJAAQAGAAAIgFIAAALQgHAEgIAAQgJAAgEgFgAi8B0QgIgJgBgNQABgNAIgIQAJgJAOAAQANAAAJAJQAJAIAAAOQAAAMgJAJQgJAIgNAAQgOAAgJgIgAizBQQgGAGABAIQgBAJAGAFQAFAFAJAAQAJAAAEgFQAGgGAAgIQAAgIgGgGQgFgFgIAAQgJAAgFAFgAlfB8IgRgpIgRApIgEAAIgag8IAMAAIAQAkIAPgkIAIAAIAPAkIAPgkIANAAIgaA8gAFtB7IAegwIgdAAIAAgLIAyAAIggAwIAgAAIAAALgAD3B7IAfgwIgdAAIAAgLIAyAAIggAwIAgAAIAAALgADLB7IAAg7IALAAIAAAOIABgBQAIgOAJAAQAGAAAIAHIgHAKQgFgGgFAAQgHAAgDAGQgEAFgBAHIAAAfgABIB7IAAgkQAAgHgDgEQgDgEgFAAQgEAAgDACQgDACgEAFIAAAqIgNAAIAAhZIANAAIAAAmQAGgJAMAAQAFAAAFADQAFADACAFQACAFABALIAAAhgAjdB7IAAgjIgLAIIAAgKIALgIIAAgsIAMAAIAAAiIAKgIIAAAKIgKAJIAAAsgAkbB7IAegwIgdAAIAAgLIAyAAIgfAwIAfAAIAAALgAgogMQAEgBACgEQADgEAAgEIAAhDIAMAAIAABDQAAAPgMAHgACoglQgGgEgDgGQgEgHAAgJQAAgOAHgIQAIgJAMAAQAMAAAHAJQAHAIAAANIAAACIgpAAQAAAIAFAFQAFAFAIAAQAMAAAJgHIAAAMQgEADgGACQgFABgHAAQgKAAgGgEgACshQQgEAEgBAHIAdAAQAAgHgEgEQgDgEgHAAQgGAAgEAEgAB7ghIgSgpIgRApIgDAAIgbg7IAMAAIAQAjIAPgjIAJAAIAOAjIAQgjIAMAAIgaA7gAACgpQgHgJAAgMQAAgNAHgJQAIgIAOAAQANAAAJAIQAJAJAAANQAAANgJAIQgJAIgNAAQgOAAgIgIgAAJhNQgFAGAAAJQAAAIAFAFQAGAFAJAAQAIAAAGgFQAFgFAAgJQAAgIgFgGQgGgFgIAAQgKAAgFAFgAg+gnQgHAGgIAAQgHAAgEgEQgEgEAAgGQAAgFAEgFQAEgEAIgDIAOgFIAAgDQAAgLgLAAQgJAAgJAKIAAgNQAHgIANAAQAJAAAGAFIADAFIADAFIAAAKIAAAZQAAABAAAAQAAABAAAAQABAAAAABQAAAAABAAIAHgDIAAAHIgGADIgGABQgHAAgCgGgAhGg8QgGADgCACQgCADgBADQABAEACACQACACAEAAQAFAAAFgEIAAgSgAiKgiIAAg6IAMAAIAAAMQAIgOAJAAQAHAAAHAHIgGAKQgGgFgFAAQgHAAgDAFQgEAFAAAIIAAAegAiggiIgegeIAagcIAPAAIgZAcIAeAegAjJgiIAAhZIALAAIAAA7IAAAegAgehpQgCgCAAgDQAAgBAAgBQAAAAAAgBQAAAAABgBQAAAAABgBQACgCACAAQABAAABAAQAAAAABAAQAAAAABABQAAAAABABQACACAAADQAAADgBACQgCABgEAAQgCAAgCgBgAEBiiIATgrIgVguIgbA8IgEAAIgRgpIgRApIgEAAIgag8IANAAIAPAjIAPgjIAJAAIAPAjIAPgjIAZAAIAQAhIAPghIANAAIgpBZgAiaiiIAAhZIAUAAQAQAAAIAIQAJAHAAAPQAAANgIAIQgJAJgMAAQgGAAgHgDIAAAggAiPjMQAFADAHAAQAIAAAEgGQAGgGAAgIQAAgGgDgFQgCgEgEgCQgEgCgJAAIgIAAgAB2jEQgGgDgEgHQgDgHgBgJQABgOAHgIQAIgIAMAAQALAAAHAIQAIAIAAAOIAAABIgqAAQABAJAFAFQAFAFAIAAQAMAAAJgHIAAALQgFAEgFABQgGACgHAAQgKAAgFgFgAB6jvQgEAEgCAHIAeAAQgBgHgEgEQgDgDgGAAQgGAAgEADgAAajEQgGgDgEgHQgDgHAAgJQAAgOAIgIQAHgIAMAAQAMAAAHAIQAHAIAAAOIAAABIgqAAQABAJAFAFQAGAFAHAAQAMAAAKgHIAAALQgFAEgGABQgFACgHAAQgKAAgGgFgAAejvQgEAEgCAHIAeAAQAAgHgEgEQgDgDgHAAQgGAAgEADgAjcjFQgIAGgIAAQgGAAgEgFQgFgDAAgHQAAgFAFgFQADgEAIgDIAPgFIAAgDQAAgKgLAAQgJAAgKAKIAAgNQAIgIAMAAQAKAAAFAFIAEAEIACAFIAAAKIAAAZQAAABAAABQAAAAAAABQABAAAAAAQABAAAAAAQADAAAEgDIAAAHIgHAEIgEABQgIAAgBgGgAjkjbQgGADgCACQgDADAAADQAAAEADACQABADAFAAQAFAAAFgFIAAgRgABPjAIAAhaIALAAIAABagAgrjAIAfgwIgeAAIAAgLIAwAAIgdAwIAdAAIAAALgAhYjAIAAg7IANAAIAAAMQAIgNAJAAQAGAAAHAGIgFALQgHgGgFAAQgFAAgFAFQgDAGAAAHIAAAfgAkzjAIAfgwIgeAAIAAgLIAzAAIggAwIAgAAIAAALg");
	this.shape.setTransform(115.3,113.7,0.912,0.912);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#C82059").s().p("Ai6BRQgUgdAAg0QAAgzAUgdQAUgeAiAAQAiAAATAeQATAdAAAzQAAAzgSAeQgTAdgjAAQgjAAgTgdgAiYg2QgGAPAAApQAAAlAGAPQAGAQAOAAQANAAAGgQQAFgQAAgpQAAgkgFgPQgGgOgOAAQgNAAgGAOgACJBsIAAhMIgYAUIAAglIAYgSIAAhnIAuAAIAABGIAYgUIAAAlIgYATIAABsgAgnBsIBJhxIhCAAIAAggICMAAIhKBxIBKAAIAAAgg");
	this.shape_1.setTransform(116.2,68.3,0.912,0.912);

	// Warstwa 1
	this.instance_1 = new lib.Ellipse1copy();
	this.instance_1.setTransform(116.7,97.8,1.039,1.039,0,0,0,60.5,60.5);

	this.addChild(this.instance_1,this.shape_1,this.shape,this.instance);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(53.5,35.5,126,126.1);


(lib.img11_1 = function() {
	this.initialize();

	// Warstwa 2
	this.instance = new lib.ludziki();
	this.instance.setTransform(80.4,128.2,0.6,0.6,0,0,0,176.8,121);

	this.addChild(this.instance);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(0.2,17.2,163.6,214.8);


(lib.GFX = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// KULA24
	this.instance = new lib.KULA24();
	this.instance.setTransform(476,131.7,1,1,0,0,0,128,89.7);
	this.instance.alpha = 0.109;
	this.instance._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(69).to({_off:false},0).to({x:389,alpha:1},6).wait(88).to({x:340.1,alpha:0.109},5).to({_off:true},1).wait(101));

	// KULA23
	this.instance_1 = new lib.KULA23();
	this.instance_1.setTransform(461.5,134,1,1,0,0,0,204,17);
	this.instance_1.alpha = 0.109;
	this.instance_1._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(69).to({_off:false},0).to({x:389,alpha:1},6).wait(88).to({x:325.6,alpha:0.109},5).to({_off:true},1).wait(101));

	// KULA22
	this.instance_2 = new lib.KULA22();
	this.instance_2.setTransform(261,81.7,1,1,0,0,0,68,63.7);
	this.instance_2.alpha = 0.109;
	this.instance_2._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_2).wait(69).to({_off:false},0).to({x:203,alpha:1},6).wait(88).to({x:125.1,alpha:0.109},5).to({_off:true},1).wait(101));

	// KULA21
	this.instance_3 = new lib.KULA21();
	this.instance_3.setTransform(425.5,120.7,1,1,0,0,0,382,107.7);
	this.instance_3.alpha = 0.109;
	this.instance_3._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_3).wait(69).to({_off:false},0).to({x:382,alpha:1},6).wait(88).to({x:289.6,alpha:0.109},5).to({_off:true},1).wait(101));

	// img11
	this.instance_4 = new lib.img11_1();
	this.instance_4.setTransform(257.5,117,1,1,0,0,0,82,117);
	this.instance_4.alpha = 0.219;

	this.timeline.addTween(cjs.Tween.get(this.instance_4).to({x:173,alpha:1},7,cjs.Ease.get(0.5)).wait(57).to({x:129.5,alpha:0.109},4).to({_off:true},1).wait(201));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(175.7,17.2,163.6,214.8);


(lib.BG = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// grad
	this.instance = new lib.gradrad();
	this.instance.setTransform(721.3,62.2,2.211,0.8,0,0,0,86.2,86.2);
	this.instance.alpha = 0.52;

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.instance}]}).wait(270));

	// grad
	this.shape = new cjs.Shape();
	this.shape.graphics.lf(["rgba(255,255,255,0)","#FFFFFF"],[0,1],-33,90,229.8,-121.8).s().p("EgrlARqMAAAgjTMBXKAAAMAAAAjTg");
	this.shape.setTransform(678.9,99.3);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape}]}).wait(270));

	// Warstwa 4 (mask)
	var mask = new cjs.Shape();
	mask._off = true;
	mask.graphics.p("AqsY3MAAAgxtMBX5AAAMAAAAxtg");
	mask.setTransform(494.2,101.7);

	// Warstwa 2
	this.instance_1 = new lib.call();
	this.instance_1.setTransform(948.5,51.3,1,1,0,0,0,949.1,150);

	this.instance_1.mask = mask;

	this.timeline.addTween(cjs.Tween.get(this.instance_1).to({x:763.5},269).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-0.6,-98.6,1898.3,311.1);


(lib.arrow_mckopia = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Warstwa 1
	this.instance = new lib.arrowdffdg();
	this.instance.setTransform(-24.2,7.5,1,1,0,0,0,9.7,7.5);

	this.timeline.addTween(cjs.Tween.get(this.instance).to({x:-12.4},5,cjs.Ease.get(0.16)).to({x:-24.1},5,cjs.Ease.get(0.16)).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-68.6,-6.6,15.7,26.4);


(lib.KULA11 = function() {
	this.initialize();

	// img12
	this.instance = new lib.img12_1();
	this.instance.setTransform(237.7,65,0.822,0.822,0,0,0,38,27.6);

	// Ellipse 1 copy
	this.instance_1 = new lib.Ellipse1copy();
	this.instance_1.setTransform(238.7,64.8,0.98,0.98,0,0,0,60.4,60.5);

	this.addChild(this.instance_1,this.instance);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(179.1,6.1,118.9,118.9);


(lib.BABLE = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Warstwa 3
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#C82059").s().p("A9/M5IAA5xMA7/AAAIAAZxg");
	this.shape.setTransform(828.2,-182.1);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape}]}).wait(270));

	// KULA31
	this.instance = new lib.KULA31();
	this.instance.setTransform(-17.5,76.1,1,1,0,0,0,80.6,81);
	this.instance.alpha = 0.16;
	this.instance._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(169).to({_off:false},0).to({x:-129.9,alpha:1},8).wait(87).to({x:-194.9,alpha:0.172},5).wait(1));

	// KULA11
	this.instance_1 = new lib.KULA11();
	this.instance_1.setTransform(449.5,60.5,1,1,0,0,0,60.5,60.5);
	this.instance_1.alpha = 0.25;
	this.instance_1._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(19).to({_off:false},0).to({x:391.5,alpha:1},5).wait(40).to({x:300.3,alpha:0.16},4).to({_off:true},1).wait(201));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(636.2,-264.7,384.2,165.1);


(lib.arrowx = function() {
	this.initialize();

	// Warstwa 2
	this.arrow_mc = new lib.arrow_mckopia();
	this.arrow_mc.setTransform(13.6,7.3);

	this.addChild(this.arrow_mc);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-55,0.6,15.7,26.4);


(lib.buttonkopia = function() {
	this.initialize();

	// arrow
	this.bt_content = new lib.arrowx();
	this.bt_content.setTransform(-136.7,-86.5,0.702,0.702,0,0,0,15.1,15.1);

	// Warstwa 3
	this.instance = new lib.bttxt();
	this.instance.setTransform(-41.8,-87.2,0.891,0.891,0,0,0,68.7,17.6);

	// Warstwa 2
	this.instance_1 = new lib.gvc();
	this.instance_1.setTransform(-40.9,-83.1,0.891,0.891,0,0,0,99.2,23.2);
	this.instance_1.shadow = new cjs.Shadow("rgba(120,169,218,1)",1,1,7);

	this.addChild(this.instance_1,this.instance,this.bt_content);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-344.8,-111.5,197.5,47.6);


(lib.BT = function() {
	this.initialize();

	// Warstwa 2
	this.button_mc = new lib.buttonkopia();
	this.button_mc.setTransform(317.8,102.1,0.689,0.689,0,0,0,116.5,36.1);

	this.addChild(this.button_mc);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(0,0.4,136,32.8);


(lib.display_mc = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// button
	this.instance = new lib.BT();
	this.instance.setTransform(805.2,139.4,1,1,0,0,0,68,17);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.instance}]}).wait(270));

	// circle2
	this.instance_1 = new lib.BABLE();
	this.instance_1.setTransform(175.6,76.5,1,1,0,0,0,255.6,60.5);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.instance_1}]}).wait(270));

	// logo
	this.instance_2 = new lib.logomc();
	this.instance_2.setTransform(470.4,174.9,0.955,0.955,0,0,0,93.5,22);

	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("EhMPAERIAAohMCYfAAAIAAIhg");
	this.shape.setTransform(473.3,210);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape},{t:this.instance_2}]}).wait(270));

	// txt
	this.instance_3 = new lib.TXT();
	this.instance_3.setTransform(827.2,71.7,0.87,0.87,0,0,0,498.8,60.5);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.instance_3}]}).wait(270));

	// GFX
	this.instance_4 = new lib.GFX();
	this.instance_4.setTransform(809.8,86,1,1,0,0,0,382,118);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.instance_4}]}).wait(270));

	// legal
	this.instance_5 = new lib.legal();
	this.instance_5.setTransform(888.4,168,1,1,0,0,0,116.6,5.4);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.instance_5}]}).wait(270));

	// grad
	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.lf(["rgba(84,142,191,0)","rgba(84,142,191,0.502)","#548EBF","rgba(84,142,191,0.749)","rgba(84,142,191,0)"],[0,0.251,0.427,0.667,1],-39.9,0,40.1,0).s().p("AmPVkMAAAgrHIMfAAMAAAArHg");
	this.shape_1.setTransform(438.4,99.3,1,1,0,0,0,5.4,0);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_1}]}).wait(270));

	// BG
	this.instance_6 = new lib.BG();
	this.instance_6.setTransform(375,100,1,1,0,0,0,375,100);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.instance_6}]}).wait(270));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-14.7,-248.7,1003.2,486.1);

})(lib = lib||{}, images = images||{}, createjs = createjs||{});
var lib, images, createjs;